### ISSUE TITLE
Don't trigger tests on package tag, version bump

### ISSUE THREAD

**Issue by esteele** [plone/jenkins.plone.org#100]
I believe we have a [no ci] tag or similar that prevents Jenkins from running tests on a commit. I'd like this to automatically get added to zest.releaser's (or plone.releaser's) tagging and version bump commits.

**Comment by gforcada** [comment]
With the recent changes from @mauritsvanrees, still unreleased, on zest.releaser isn't this partially solved?

mr.roboto needs to be updated (maybe) @bloodbare could you shed some light here? A quick github search on mr.roboto only shows one result: https://github.com/plone/mr.roboto/search?utf8=%E2%9C%93&q=skip does that mean that is not implemented?

**Comment by gforcada** [comment]
@bloodbare @esteele I see that instead of ``[ci skip]`` mr.roboto looks for ``[fc]``: https://github.com/plone/mr.roboto/blob/master/src/mr.roboto/src/mr/roboto/views/runcorejob.py#L95

So I guess that ``[fc]`` plus @mauritsvanrees changes on zest.releaser will give you what you need, right?

**Comment by mauritsvanrees** [comment]
With https://github.com/zestsoftware/zest.releaser master (or 4.0 once we release that) these lines in `setup.cfg` in a package or globally in your `~/.pypirc` will do the trick:

```
[zest.releaser]
extra-message = [fc]
```

What does the `fc` stand for?  Fake commit?

**Comment by gforcada** [comment]
@mauritsvanrees yes I think so, we could of course just change it to something else though...

**Comment by gforcada** [comment]
@esteele closing this as zest.releaser 4.0 + [fc] should be enough, confirm and reopen if needed.

**Comment by mauritsvanrees** [comment]
Actually, mr.roboto only looks at the [first line of the commit message](https://github.com/plone/mr.roboto/blob/master/src/mr.roboto/src/mr/roboto/views/runcorejob.py#L95), and even then only at the first 60 characters:

```
short_commit_msg = commit['message'].split('\n')[0][:60]
```

With the new zest.releaser, a commit message would be something like this:

```
Back to development x.y

[fc]
```

So it looks like this won't work currently. I have not tried it. mr.roboto could be changed to look in the complete commit message.

**Comment by gforcada** [comment]
Related to https://github.com/plone/jenkins.plone.org/issues/128

**Comment by mauritsvanrees** [comment]
The linked pull request should help.

Note that above we are talking about an `[fc]` tag, but that is the tag that mr.roboto adds to fake commits that it itself makes to coredev. That commit is what makes Jenkins start up jobs again, if I see it correctly.

My mr.roboto pull request basically solves it by not creating these fake commits when there is a `[ci skip]` tag in the base commit. The `versions_to_commit` variable then remains an empty list, which means nothing is committed to any of the coredev branches.

Warning: when I write it like this, it sounds logical to me, but I may be mistaken in how mr.roboto and Jenkins work together. Also: I cannot test it.

**Comment by gforcada** [comment]
@mauritsvanrees can we close this one now?

**Comment by mauritsvanrees** [comment]
Yes!
It's working fine so far for me.
