### ISSUE TITLE
Create a job to handle the dist.plone.org deploy step for releases

### ISSUE THREAD

**Issue by esteele** [plone/jenkins.plone.org#101]
build.plone.org used to have a job that downloaded all packages (plus versions.cfg) and pushed them to a specified directory on dist.plone.org. It'd save me a lot of time to have that running again.

**Comment by tisto** [comment]
@esteele I would like to work on that for the upcoming releases. We would need make sure that jenkins has access to dist.plone.org. I can then create a jenkins job that you can trigger manually to do the upload.

**Comment by esteele** [comment]
@tisto I don't have sudo rights. I think @martior should be able to give you access.

**Comment by tisto** [comment]
@esteele how do we get a list of all releases and versions that we need to upload? Is is sufficient to parse versions.cfg and upload all packages under the "# Plone release" line?

https://github.com/plone/buildout.coredev/blob/5.0/versions.cfg#L88

**Comment by esteele** [comment]
We upload everything. I have a cfg that I run buildout against to get a full downloads cache, pulling everything from releases pinned in versions.cfg

```
[buildout]
extends = core.cfg

eggs-directory = release-cache/eggs
download-cache = release-cache/downloads
extends-cache = release-cache/extends

auto-checkout =
```

**Comment by gforcada** [comment]
Closing in favor of #175
