### ISSUE TITLE
Send weekly changelog summaries to esteele

### ISSUE THREAD

**Issue by esteele** [plone/jenkins.plone.org#102]
I'd like a weekly email listing all of the changelog entries added since the previous release. There should be two methods in plone.releaser that'd be fairly close to doing this.

**Comment by gforcada** [comment]
@esteele this basically means sending you by email the output of ``./bin/manage report`` ?

**Comment by esteele** [comment]
Yes. I never remember to do it myself.

**Comment by gforcada** [comment]
I guess you already got the first weekly email from the new Jenkins job: http://jenkins.plone.org/view/All/job/pending-releases

Reopen this issue if that was not what you were expecting.
