### ISSUE TITLE
Create check for README and /docs on repos 

### ISSUE THREAD

**Issue by svx** [plone/jenkins.plone.org#103]
create a check which checks if the repositories include a docs folder and have a readme, send output to Sven or have the output as file somewhere.

**Comment by gforcada** [comment]
@svx I'm working on it right now... keep an eye on http://jenkins.plone.org/view/All/job/docs-package-styleguide (better names for the job are welcomed :)

**Comment by gforcada** [comment]
@svx while waiting for a better name I'm closing this.

Let me know if it needs to do something more (or less).
