### ISSUE TITLE
jenkins_node.yml vs plone.jenkins_node

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#104]
While trying to add python3.4 support on jenkins nodes I realized that the ansible configuration for nodes is not taken from the ansible galaxy playbook (i.e. [plone.jenkins_node](https://github.com/plone/plone.jenkins_node)) but instead from [jenkins_node.yml](https://github.com/plone/jenkins.plone.org/blob/master/jenkins_node.yml).

Doing a cross-check between them they look *sort of the same*, so the question is simple: we don't want two different node configurations, so which one should prevail?

I've spend quite a few hours working on the plone.jenkins_node ansible playbook, it runs without a problem locally but I still miss the final connection with the master, so I can't be sure that tests will run there without a problem.

**Comment by gforcada** [comment]
I can take one node (say node4) and use the plone.jenkins_node there until everything works as expected, I don't expect much hiccups...

**Comment by tisto** [comment]
+1

**Comment by gforcada** [comment]
The pull request take over the discussion.
