### ISSUE TITLE
Munin for jenkins nodes.

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#107]
We have munin for the jenkins server. It would be nice to include our nodes there as well.

**Comment by gforcada** [comment]
I started some work on this in both the master and nodes roles. I'm using geerlingguy.munin and munin-node. Nothing is deployed so far, I only played with it on vagrant.

**Comment by gforcada** [comment]
Is there already for quite a while: http://jenkins.plone.org/munin/
