### ISSUE TITLE
Javascript unit testing

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#108]
Given that with Robot Framework only small parts of our growing JavaScript code is tested and that mockup already has a testing framework on it, wouldn't be needed to set up a jenkins job for running those as well?

@vangheem @frapell @thet if I got it correctly from mockup's README, Jenkins only needs to:

```
git clone mockup
make bootstrap
make test
```

Am I missing something? And even more important, do we have more JavaScript unittests somewhere not covered by mockup's ``make test``? How far is the integration with Patternslib? Do we want to also run its tests as well?

**Comment by frapell** [comment]
@gforcada I think you might want to use `make test-once` instead of `make test` since the latter will keep waiting on modified files to run again automatically.

I don't know the answer to your other questions

**Comment by gforcada** [comment]
@frapell yes I noticed that after waiting 5 minutes or so to the jenkins job to finish :)

**Comment by gforcada** [comment]
The only thing missing is making a new mockup-core release (for the test_jenkins karma configuration) and adding it on jenkins.plone.org core tab.

Afterwards we can keep adding browsers (right now only PhantomJS).
