### ISSUE TITLE
Notify, via email, that someone broke the build

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#110]
Our jenkins setup is tested enough so we can go one step further and start notifying the developer that broke the build.

Right now if a commit breaks the build only plone-testbot@lists.plone.org is notified. https://github.com/plone/jenkins.plone.org/blob/master/jobs.yml#L1011

We should expand that to also notify the one that broke the build.

**Comment by tisto** [comment]
+1 That would be awesome!

**Comment by gforcada** [comment]
Rather than mail, we should ping discord or some other more fashionable means I would say...

**Comment by gforcada** [comment]
We already report that on GitHub PRs statuses 🎉
