### ISSUE TITLE
Jenkins dependencies jobs are broken

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#113]
http://jenkins.plone.org/view/Dependencies/

**Comment by gforcada** [comment]
I broke them while playing with mr.developer, will fix them right now, finally I have some time again, sorry for breaking them!

**Comment by gforcada** [comment]
Ok, so it's not my fault actually but the recent changes made on buildout.coredev, will look into them as well

**Comment by gforcada** [comment]
Fixed long ago.
