### ISSUE TITLE
PR 4.3 jobs are red - not because of the PRs it seems

### ISSUE THREAD

**Issue by jensens** [plone/jenkins.plone.org#114]
from plone-developers list copied:

Hi,

i just found that in several packages the pull request testing fails for
4.3.

for example here http://jenkins.plone.org/job/pull-request-4.3/24/
but in fact all are currently failing
http://jenkins.plone.org/job/pull-request-4.3/ - and only a few because
of real failures as it seems.

May one of testing team have a look please? I cant help here.

regards
Jens

**Comment by gforcada** [comment]
Seems to be fixed already, there are some green  builds on http://jenkins.plone.org/job/pull-request-4.3
