### ISSUE TITLE
Robot test failling "OSError: [Errno 12] Cannot allocate memory"

### ISSUE THREAD

**Issue by ebrehault** [plone/jenkins.plone.org#115]
On PLIP - 13350-edit-member-schema-ttw, all the robot tests are failling with the following error:
```
OSError: [Errno 12] Cannot allocate memory
```
Example:
http://jenkins.plone.org/job/plip-13350-edit-member-schema-ttw/12/robot/Robot/Test%20Edit%20User%20Schema/Min%2Fmax%20constraint%20is%20honored/

Anybody heard of something similar?
Is there any special to do in the buildout to avoid memory leaks?

**Comment by gforcada** [comment]
That specific job was running at the same time as another job in Node1, maybe that was a bit too much? We still don't have munin installed, so it's hard to say afterwards if there was really a resource problem or not...

You can try to run it again a bit later once there are not so many jobs running.

**Comment by tisto** [comment]
Follow up: https://github.com/plone/jenkins.plone.org/issues/121

Will close this one.
