### ISSUE TITLE
PR-Testing: please remove default to p.a.discussion

### ISSUE THREAD

**Issue by jensens** [plone/jenkins.plone.org#116]
It is annoying to always have to remove the default value. 
Also this lead to mistakes.
So please remove default value for build with parameters.
Help/Description of the field says anyway what to fill in there.

**Comment by jensens** [comment]
i think its here: https://github.com/plone/jenkins.plone.org/blob/master/jobs.yml#L704

**Comment by gforcada** [comment]
I thought it was useful, but if it leads to errors... gone.

**Comment by jensens** [comment]
for the very first time use its useful, afterwards it always additional step delete-before-paste which may result in wrong pastes.
