### ISSUE TITLE
github post-commit hooks use server IP instead of the domain name.

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#118]
http://78.47.49.108/roboto/run/corecommit

should be:

http://jenkins.plone.org/roboto/run/corecommit

cc @bloodbare

**Comment by gforcada** [comment]
I think the problem is that jenkins.plone.org points to cloudflare and then the redirects don't work as expected? We could create a master.plone.org?

**Comment by bloodbare** [comment]
Exactly, if we point to jenkins.plone.org there is some errors with
cloudflare.

R

El dj., 18 juny 2015 a les 11:12, Gil Forcada Codinachs (<
notifications@github.com>) va escriure:

**Comment by tisto** [comment]
Right. Ok, then let's leave it as it is...
