### ISSUE TITLE
Add "build with parameters" link prominently

### ISSUE THREAD

**Issue by thet** [plone/jenkins.plone.org#119]
Every time, I want to build a pull request on jenkins.plone.org, I have to search for a really long time for the link to "build with parameters". Today, I gave up and file instead a ticket here:

If this is easily doable, please provide a prominent link on the start page and each subpage to make a "build with parameters". If it's really easy, we should rethink the whole jenkins menu structure - most of the links do not make much sense in our context.

@tisto  @gforcada

**Comment by thet** [comment]
Finally i found it, by following a link where i successfully did a build with parameters for plone 5:
http://jenkins.plone.org/job/pull-request-5.0/build

**Comment by tisto** [comment]
Good idea. Will look into it...

**Comment by thet** [comment]
I'm using this ticket as a bookmark in the meantime :)

**Comment by gforcada** [comment]
@thet refresh your browser and let me know if it's prominent enough already :-)
