### ISSUE TITLE
Remove Docker and Pull Request jobs from "Core" tab.

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#120]
Core tab should just contain the Core jobs. We should create separate tabs for pull requests and docker.

**Comment by gforcada** [comment]
While I agree with the docker one I'm kind of +0 with pull requests jobs... the more easier to find them the best, although I would not argue match about it, so if there are more people willing to change that go ahead.

**Comment by jensens** [comment]
seems that docker tab is already gone?
Anyway, if this is still an topic, please keep PR there. If you plan to remove them anyway, at least add an own main tab for PRs.

**Comment by gforcada** [comment]
Can we close this and leave it like it is? Docker is gone but PR stay.
