### ISSUE TITLE
jenkins.plone.org nodes are dead: No space left on device

### ISSUE THREAD

**Issue by jensens** [plone/jenkins.plone.org#123]
Second time, look like a missing cleanup of something (log cycling?)

**Comment by gforcada** [comment]
A ``/var/log/jenkins/jenkins.log`` (there logrotate in place) of **26Gb** just made master impossible to work on.

Some sort of DDOS? This issue on jenkins seems to be close to what happened: https://issues.jenkins-ci.org/browse/JENKINS-10160

**Comment by pbauer** [comment]
jenkins is dead again

**Comment by gforcada** [comment]
The same (fortunately or not) again. ``/var/log/jenkins/jenkins.log`` was 32Gb...
