### ISSUE TITLE
Unknown entry point or macro 'disk-usage' for component type: 'property'

### ISSUE THREAD

**Issue by datakurre** [plone/jenkins.plone.org#125]
I have vagrant master up and Jenksin is available at locahost:8080 (I had to do vagrant up, vagrant provision and vagrant reload to get up to that point).

    $ vagrant provision master
    ...
    PLAY RECAP ******************************************************************** 
    master                     : ok=34   changed=8    unreachable=0    failed=0 

When I run

    $ jenkins-jobs --conf jenkins.ini.in update jobs.yml

I get error

    INFO:root:Updating jobs in ['jobs.yml'] ([])
    Traceback (most recent call last):
    ...
    jenkins_jobs.errors.JenkinsJobsException: Unknown entry point or macro 'disk-usage' for component type: 'property'.

**Comment by gforcada** [comment]
Sorry to go back so late to you... are you using the jjb fork found on my account? You need to enable it manually, sorry did not spend the time to configure properly with mr.developer.

The docs explain everything though: http://jenkinsploneorg.readthedocs.org/en/latest/setup.html

Reopen if it still happens.

**Comment by datakurre** [comment]
@gforcada Thanks. It was most probably that I was not using your fork of jjb. For some reason I failed to see that as requirement.
