### ISSUE TITLE
Allow to test multiple pull requests.

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#126]
We could extend the pull request jobs to allow to paste multiple pull request URLs. Right now we have to create a PLIP job for those kind of pull requests. It shouldn't be too hard to test multiple checkouts instead of just one. Any takes?

**Comment by gforcada** [comment]
So basically adding a loop on https://github.com/plone/jenkins.plone.org/blob/master/jobs.yml#L743-L757 ?

That seems easy, OTOH a PLIP job ensures that other developers can check that code as well, not just you and jenkins (provided you give to it all the pull requests)

**Comment by tisto** [comment]
Yes. That was my idea. We can still use the PLIP job for more complex
use cases. Sometimes the PLIP job is just overkill though.

Am 07.09.2015 um 13:40 schrieb Gil Forcada Codinachs:

**Comment by jensens** [comment]
big :+1: for the feature

**Comment by mauritsvanrees** [comment]
Sounds elegant.

**Comment by gforcada** [comment]
I'm running a jenkins job with two pull requests on it: http://jenkins.plone.org/view/All/job/pull-request-5.0/519/console :-)

Once that shows green I will push the code and close this issue.

**Comment by jensens** [comment]
yeah!

**Comment by tisto** [comment]
AWESOME!!! Thanks @gforcada!

**Comment by davisagli** [comment]
@gforcada your blog post says to let you know if this does not work as expected. Well, I'm not quite sure what to expect. Just put each pull request URL on a separate line? Where's the documentation?

**Comment by gforcada** [comment]
@davisagli yes, one per line, and thanks for the reminder, I actually added it here: http://jenkins.plone.org/job/pull-request-5.0/build but forget the push the changes to jenkins. Now it should be shown there.

**Comment by davisagli** [comment]
@gforcada good, thanks!
