### ISSUE TITLE
Feature: Use github status api to report back to github PR

### ISSUE THREAD

**Issue by jensens** [plone/jenkins.plone.org#127]
Github has a status api described here
https://developer.github.com/v3/repos/statuses/

This API enables us to report back to github from jenkins. 
When a PR jenkins job is triggered it is possible to set the status at github ``pending``. After it finishes the state maybe set to ``success``, ``error``, or ``failure``.

**Comment by jensens** [comment]
Btw.: The label ``pr testing`` would become superfluos, because even in the list at https://github.com/pulls?user=plone the check status is shown.

**Comment by gforcada** [comment]
That's something I wanted to implement for quite some time, too many tings to do, but indeed it would be great to integrate it.

**Comment by tisto** [comment]
We played around with that feature when we build mr.roboto. It works, it is just a matter of taking the time to implement it...

**Comment by gforcada** [comment]
See https://github.com/plone/jenkins.plone.org/pull/131

**Comment by jensens** [comment]
this works now, but one minor issue left:
For packages PR tested for 4.3 AND 5.0 its reports back to the same, so one overrules the other.

**Comment by gforcada** [comment]
@jensens true, I will fix that. Thanks for noticing it!

**Comment by gforcada** [comment]
@jensens should be fixed with https://github.com/plone/jenkins.plone.org/commit/3918fed40bb4a3c13eed43ed35e02bf904dc28f9

**Comment by jensens** [comment]
thanks!! i think we can close this one now. all done.
