### ISSUE TITLE
Create a job to run statistics.py for translations stats

### ISSUE THREAD

**Issue by vincentfretin** [plone/jenkins.plone.org#133]
Create a job to run the statistics.py script to have some translations stats and publish it somewhere as plain/text file through nginx.
There is actually two commands to execute, see the beginning of the script:
https://github.com/collective/plone.app.locales/blob/master/utils/statistics.py
You need the gettext package on the server to have the command msgfmt.

The script gives the following output:

```
pl	: 1971 (65.70%) / 46 / 983 = 3000
	atcontenttypes: 169/0/0 = 169
	atreferencebrowserwidget: 10/0/5 = 15
	cmfeditions: 65/0/0 = 65
	cmfplacefulworkflow: 52/3/3 = 58
	passwordresettool: 31/0/1 = 32
	plone: 1584/43/767 = 2394
	plonefrontpage: 11/0/0 = 11
	plonelocales: 49/0/0 = 49
	widgets: 0/0/207 = 207

ta	: 264 (8.83%) / 60 / 2665 = 2989
	atcontenttypes: 7/3/159 = 169
	atreferencebrowserwidget: 0/0/15 = 15
	cmfeditions: 3/1/61 = 65
	cmfplacefulworkflow: 0/1/57 = 58
	passwordresettool: 0/0/32 = 32
	plone: 235/55/2104 = 2394
	/!\ plonefrontpage file missing
	plonelocales: 19/0/30 = 49
	widgets: 0/0/207 = 207

fr	: 2950 (98.33%) / 2 / 48 = 3000
	atcontenttypes: 169/0/0 = 169
	atreferencebrowserwidget: 15/0/0 = 15
	cmfeditions: 65/0/0 = 65
	cmfplacefulworkflow: 58/0/0 = 58
	passwordresettool: 32/0/0 = 32
	plone: 2344/2/48 = 2394
	plonefrontpage: 11/0/0 = 11
	plonelocales: 49/0/0 = 49
	widgets: 207/0/0 = 207

```

**Comment by vincentfretin** [comment]
refs https://github.com/plone/Products.CMFPlone/issues/983

**Comment by vincentfretin** [comment]
We can modify the script to create an output in a different format (html table, progress bar for example). If anybody want to contribute this, please do.

**Comment by gforcada** [comment]
@vincentfretin there is a full blown django app called damned-lies used by the GNOME project, that's probably a bit far fetched, but the user interface is really nice and has lots of ideas worth stealing:

Website: http://l10n.gnome.org/
Source code: https://git.gnome.org/browse/damned-lies/

Something like this would be awesome to have for Plone i18n:
https://l10n.gnome.org/releases/gnome-3-20/

**Comment by gforcada** [comment]
**done!**

Job http://jenkins.plone.org/view/QA/job/qa-i18n-statistics

@vincentfretin can you double check your statistics script though, it's giving an error: http://jenkins.plone.org/view/QA/job/qa-i18n-statistics/1/console

**Comment by vincentfretin** [comment]
You introduced a bug ;) The produced raw_numbers.txt was only one line, it should have 529 lines in it. I fixed it in jobs.yml. You need to redeploy I guess.

**Comment by vincentfretin** [comment]
Having an l10n interface like the one GNOME has would be great indeed. Like I said, we can modify our statictics.py script to produce an html table with the same class and steal the css from damned lies. :)

**Comment by gforcada** [comment]
@vincentfretin thanks for fixing the code, sorry for messing it up!

Pushed, it should work now

**Comment by gforcada** [comment]
It's not just about displaying statistics you can also commit translations from within it, has a translation workflow and what not, if you have some time look at it, it's really cool (although hard, I  guess, to reuse for Plone...)
