### ISSUE TITLE
plone.namedfile changes missing in coredev 4.3

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#134]
In coredev 4.3 I have checked out plone.namedfile: https://github.com/plone/buildout.coredev/commit/6621319b7a42f9ec5b6e9197892c293e476ffa81

Then I did a change in plone.namedfile:
https://github.com/plone/plone.namedfile/commit/d6c010ab25c7bf153e92a791e3b560ef6fd3ae5a

I should have done that as a pull request, sorry.

But the change is not ending up in coredev 4.3 in `last_commit.txt`. Is something not running?

**Comment by gforcada** [comment]
There's something wrong indeed: https://github.com/plone/buildout.coredev/settings/hooks/4240219

**Comment by gforcada** [comment]
Seems that somehow mr.roboto was stopped on jenkins.plone.org master and I think I'm the one on blame, as I was playing with it for https://github.com/plone/jenkins.plone.org/pull/131 and I probably left it stopped...

Thanks for noticing!

I already started a job for all the main ones, hopefully nothing broke during these days!

**Comment by mauritsvanrees** [comment]
Looks good, I see one auto commit coming in on 4.3 now.  Thanks.

**Comment by gforcada** [comment]
Actually that's interesting: even though the automatic commits where not triggered, as *everyone* is using the pull requests jobs and do not merge if they fail the master jobs are still working...
