### ISSUE TITLE
Test report file was length 0

### ISSUE THREAD

**Issue by Gagaro** [plone/jenkins.plone.org#138]
Hello,

I have an issue with one of my PR (https://github.com/plone/plone.app.content/pull/67). I have these errors I do not understand and that I can't reproduce locally:

    Test report file /home/jenkins/workspace/pull-request-5.0/parts/test/testreports/plone.app.caching.tests.test_operation_utils.MiscHelpersTest.xml was length 0

http://jenkins.plone.org/job/pull-request-5.0/639/testReport/
http://jenkins.plone.org/job/pull-request-5.0/640/testReport/

The tests does not seem to be linked to my PR. Is this a jenkins bug?

Thanks

**Comment by gforcada** [comment]
@Gagaro I don't see that string on http://jenkins.plone.org/job/pull-request-5.0/639/consoleFull nor on http://jenkins.plone.org/job/pull-request-5.0/640/consoleFull

But anyway if that happens, the script responsible of that should be this one: https://github.com/plone/jenkins.plone.org/blob/master/scripts/pr-update-status.py

**Comment by gforcada** [comment]
That was a "no space left on device" problem fixed by @tisto

**Comment by msant0** [comment]
@gforcada the links you sent are currently down, would you have any new material to solve the problem? I am facing the same situation.

**Comment by msant0** [comment]
> That was a "no space left on device" problem fixed by @tisto

@gforcada the links you sent are currently down, would you have any new material to solve the problem? I am facing the same situation.

**Comment by gforcada** [comment]
Unfortunately not, where are you seeing that? :thinking:

**Comment by msant0** [comment]
> Infelizmente não, onde você está vendo isso? 🤔
I was able to find my problem, I'm having version problems even on nodejs together with phantom-js, in this file I create the test reports file
