### ISSUE TITLE
Broken: 4.3 PR jobs 

### ISSUE THREAD

**Issue by jensens** [plone/jenkins.plone.org#139]
This happens now since dec. 13th
tests passed, then see
http://jenkins.plone.org/view/All/job/pull-request-4.3/194/console
also jenkins reporting to github does not work (even not at start of the job).

    Recording test results
    ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
    Robot results publisher started...
    -Parsing output xml:
    Failed!
    hudson.AbortException: No files found in path /home/jenkins/workspace/pull-request-4.3/parts/test with configured filemask: robot_output.xml
    ...
    at hudson.model.Executor.run(Executor.java:410)
    Started calculate disk usage of build
    Finished Calculation of disk usage of build in 0 seconds
    Started calculate disk usage of workspace
    Finished Calculation of disk usage of workspace in 0 seconds
    Email was triggered for: Always
    Sending email for trigger: Always
    Sending email to: jens@bluedynamics.com
    Finished: FAILURE

**Comment by jensens** [comment]
update: it reported back (as green). but on start it does not reported it. anyway, something is broken.

**Comment by gforcada** [comment]
@jensens it did report at the beginning, but on a different commit, see the two commits on https://github.com/plone/Products.CMFPlacefulWorkflow/pull/8/commits

For whichever reason jenkins started only when one commit was there, and hence https://github.com/sixfeetup/Products.CMFPlacefulWorkflow/commit/231a6c53a4ee3c0f2e7f9c98cce2f5bd402a3bb8 has the yellow ball, but when jenkins finished there was another commit so jenkins reported to that commit: https://github.com/sixfeetup/Products.CMFPlacefulWorkflow/commit/7d919ffa158720d7aa45f6efba7048c3c320697b

Do I see

**Comment by gforcada** [comment]
@jensens but you are right that robot framework tests report to different places on 5.0 and 4.3 jobs and that's still not solved.

**Comment by gforcada** [comment]
@jensens thanks for reporting and taking the time to debug/inspect what happens. I think I fixed it, at least the robot framework part.

**Comment by gforcada** [comment]
@jensens and all now it should be really fixed with https://github.com/plone/jenkins.plone.org/commit/2fb781242c860da47dc6954f125cf32b713aa674 maybe there are other problems though, but concerning not finding the test results that should be gone :-)
