### ISSUE TITLE
Failed to read test report file

### ISSUE THREAD

**Issue by jensens** [plone/jenkins.plone.org#141]
Failed to read test report file /home/jenkins/workspace/pull-request-5.0/parts/test/testreports/Products.PortalTransforms.tests.test_transforms.TransformTestSubclass.xml
org.dom4j.DocumentException: Error on line 26 of document file:///home/jenkins/workspace/pull-request-5.0/parts/test/testreports/Products.PortalTransforms.tests.test_transforms.TransformTestSubclass.xml : An invalid XML character (Unicode: 0x0) was found in the value of attribute "message" and element is "failure". Nested exception: An invalid XML character (Unicode: 0x0) was found in the value of attribute "message" and element is "failure".

http://jenkins.plone.org/job/pull-request-5.0/695/testReport/junit/Products.PortalTransforms.tests.test_transforms.TransformTestSubclass/xml/_init_/

This is either a problem with jenkins or with the module that creates the test report.

**Comment by gforcada** [comment]
That's a problem of the test, as it is about transforms, the output is most probably not encoded correctly and thus the parser fails to parse it.

As soon as the test is fixed, the parser will be able to handle it again.
