### ISSUE TITLE
workflow job is broken (on jenkins job builder side)

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#142]
With the new releases of jenkins-job-builder, there is some support for workflow based jobs.

We already have one job using it, although that was when we had on our jenkins-job-builder fork an implementation for it.

So there seems to be some differences and right now trying to re-create that job fails.

**Comment by tisto** [comment]
Do you have a link to the newly created job?

http://jenkins.plone.org/view/All/job/workflow/ is green.

**Comment by gforcada** [comment]
@tisto I meant that running ``job-builder la la la la`` fails at generating the workflow job, the job on jenkins.plone.org still works fine. Sorry for the confusion.

**Comment by gforcada** [comment]
And now on top of this brokeness we need to update it to 5.1. Does it make sense to do have it for both or only 5.1? Let me know your plans (or anyone else that feels up for the task) regarding this job.
