### ISSUE TITLE
Create a github user to write the code analysis comments

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#146]
I enabled some repositories to be monitored by jenkins.plone.org for code analysis but to not be  blocked by that I did use one access token from my user.

For pull requests that's not a problem, but for code analysis as we report it as a comment it seems that **I'm** the person writing them. See https://github.com/plone/plone.app.testing/commit/78da35120e4b5fed7466d64ca438af0269f10291 for an example.

We should create a github user and change the access token.

If I remember correctly mr.roboto used one such a user, could we reuse that one?

@bloodbare @tisto

**Comment by tisto** [comment]
@gforcada There is a jenkins user for mr.roboto already. Ping me for username/password.

**Comment by gforcada** [comment]
@tisto no need for that, you could do that yourself: create a token for that user and put it on http://jenkins.plone.org/configure on the ``GITHUB_API_KEY`` environment variable.

**Comment by gforcada** [comment]
https://help.github.com/articles/creating-an-access-token-for-command-line-use/

**Comment by gforcada** [comment]
User is jenkins-plone-org and jenkins.plone.org is already update :-)
