### ISSUE TITLE
code-analysis job: github u'message': u'body is too long (maximum is 65535 characters)'

### ISSUE THREAD

**Issue by jensens** [plone/jenkins.plone.org#147]
see http://jenkins.plone.org/view/Pkgs/job/package-plone.app.discussion/1/console

    [package-plone.app.discussion] $ python /tmp/hudson8276875491846503469.py
    Traceback (most recent call last):
      File "/tmp/hudson8276875491846503469.py", line 116, in <module>
        body=comment
      File "/usr/local/lib/python2.7/dist-packages/github/Commit.py", line 149, in create_comment
        input=post_parameters
      File "/usr/local/lib/python2.7/dist-packages/github/Requester.py", line 171, in requestJsonAndCheck
        return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
      File "/usr/local/lib/python2.7/dist-packages/github/Requester.py", line 179, in __check
        raise self.__createException(status, responseHeaders, output)
    github.GithubException.GithubException: 422 {u'documentation_url': u'https://developer.github.com/v3/repos/comments/#create-a-commit-comment', u'message': u'Validation Failed', u'errors': [{u'field': u'body', u'message': u'body is too long (maximum is 65535 characters)', u'code': u'custom', u'resource': u'CommitComment'}]}
    Build step 'Execute Python script' marked build as failure

**Comment by gforcada** [comment]
That's even more of a reason to not add automatically a job for each repository, but only when they are cleaned.

jenkins starts a job for each branch the first time it runs, so it is inevitably that some really old branches would have plenty of errors.

In a way I would say that it is a *feature* as it prevents to spam branches that anyway are not meant to be cleaned up either.

Sounds good?

**Comment by jensens** [comment]
:D ok, nice "feature"
