### ISSUE TITLE
Jenkins: No space left on device

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#150]
I have been pushing Jenkins rather hard this evening, with lots of "should be harmless" commits like adding setup.py classifiers.
I now see several failures like:
- No usable temporary directory found
- No space left on device

For example:
- http://jenkins.plone.org/job/plone-4.3-python-2.7/1165/console
- http://jenkins.plone.org/job/plone-5.0-python-2.7-at/4060/

Maybe it will all be alright if we wait an hour or so. If not: can someone take a look?

**Comment by mauritsvanrees** [comment]
Never mind, the main Jenkins jobs are all green again.

**Comment by gforcada** [comment]
No actually node3 is still at 100% of disk usage.

**Comment by gforcada** [comment]
It will not fix the issue per se, but at least it will help: https://github.com/plone/jenkins.plone.org/issues/111

**Comment by mauritsvanrees** [comment]
Node3 is still out of disk space:
http://jenkins.plone.org/job/plone-4.3-python-2.7/1174/console

**Comment by gforcada** [comment]
@mauritsvanrees I saw it and made some small cleanup, should be enough for some days... I'm really tired now, I will try to get a more permanent solution tomorrow morning

**Comment by jensens** [comment]
looks like this one hit us again:
error: could not create 'build': No space left on device
http://jenkins.plone.org/job/pull-request-5.1/179/console

**Comment by mauritsvanrees** [comment]
Several jobs have failed, four now, all are on node number 1.

**Comment by gforcada** [comment]
@mauritsvanrees I saw the report on community.plone.org and fixed it. We have lots of jobs and they do take a **lot** of space... Anyway I cleaned up a bit and now it's a bit better.

**Comment by mauritsvanrees** [comment]
Thanks, Gil.

I wonder if it makes sense to somehow make a split, so that for example the Plone 4.3 jobs always run on Node 1 or 2, and Plone 5.0 on 3 and 4. That should mean only roughly half the disk space is needed, but at the cost of more configuration...

**Comment by tisto** [comment]
@mauritsvanrees I would prefer not to bind jobs to certain nodes. We had that in the past and that drasically reduced the flexibility and led to a situation where jobs could run only on certain machines. Hardware is cheap, our time is not. Let's try to get more hardware...

**Comment by mauritsvanrees** [comment]
More hardware is certainly better. That would also reduce the need (perceived by me at least) for measures like this: https://github.com/plone/jenkins.plone.org/pull/166

**Comment by mauritsvanrees** [comment]
Having more disk usage is always good, but that does not need to be tracked here, so let's close this issue.
