### ISSUE TITLE
Move jobs from jenkins.starzel.de to jenkins.plone.org

### ISSUE THREAD

**Issue by pbauer** [plone/jenkins.plone.org#151]
We moved our companies tests to gitlab-ci and would like to kill the server and jenkins. 

On https://jenkins.starzel.de we still run two jobs:

1. CMF-trunk_Zope-trunk: At https://jenkins.starzel.de/job/CMF-trunk_Zope-trunk/ we test https://github.com/zopefoundation/CMF-buildout 
2. zopetoolkit_trunk: At https://jenkins.starzel.de/job/zopetoolkit_trunk/ we test https://github.com/zopefoundation/zopetoolkit.git

Before I try to move that to gitlab-ci (for which I would probably need to mirror the repos in our gitlab - meh): Would it not be better if we move these tests to jenkins.plone.org. I can give someone of the ci-team admin-access to our jenkins if that helps with moving.

**Comment by gforcada** [comment]
@pbauer it's sort of there already, a bit hidden though: http://jenkins.plone.org/view/Zope/ but I will take a look at them again. Could you attach their configuration (if there are no passwords/secrets)?

Just append config.xml on the job URL and you will get it, like http://jenkins.plone.org/view/Zope/job/zope-cmf-27/config.xml

**Comment by pbauer** [comment]
@mauritsvanrees said they are not tested there. I actually don't know.

Here are the configs:
[zopetoolkit-trunk_config.xml.txt](https://github.com/plone/jenkins.plone.org/files/125076/zopetoolkit-trunk_config.xml.txt)
[CMF-trunk_Zope-trunk_config.xml.txt](https://github.com/plone/jenkins.plone.org/files/125078/CMF-trunk_Zope-trunk_config.xml.txt)

**Comment by pbauer** [comment]
@gforcada thanks for setting these up. Can I shut down our old jenkins-jobs then?

**Comment by gforcada** [comment]
I would say so, at least the configuration is already saved here, so nothing gets lost

**Comment by Gomez** [comment]
Thanks @gforcada Closing as we disabled the jobs a while ago.
