### ISSUE TITLE
Jobs for 5.1

### ISSUE THREAD

**Issue by jensens** [plone/jenkins.plone.org#157]
We need PR jobs for 5.1 and "main" tests against 5.1 please.

**Comment by gforcada** [comment]
I have them ready, I just need to double check them before pushing. I fall asleep yesterday night :-)

**Comment by gforcada** [comment]
Pushed in https://github.com/plone/jenkins.plone.org/commit/6cf4c9c39a17d963970a93637cde8cc773dfad13 but there are some work still to do.

Jobs are being created.
