### ISSUE TITLE
themepreview jobs status

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#158]
@datakurre with the new 5.1 jobs, themepreview ones should be updated to that one as well? I think that since we moved to jenkins-job-builder they have never ever run.

What are your plans regarding them?

Or not just you but is someone else up for this task? Please speak (or write) up! :-)

**Comment by datakurre** [comment]
You may remove themepreview jobs for now to ease bookkeeping.  I'll ping you when I have managed to update them for the current SauceLabs tools, and if I'm unable to add them myself. I try to remember them, when I have empty slots to do community stuff.

Gil Forcada Codinachs wrote:

**Comment by gforcada** [comment]
@datakurre thanks for the quick response. I removed them from jobs.yml and on jenkins.plone.org. Let me know if you need any help bringing them back (specially on the jobs.yml part)
