### ISSUE TITLE
docker job

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#159]
@svx @bloodbare there is a jenkins jobs that creates a new build of docker if the robotframework tests do pass.

So far it was only doing 5.0 images, but now with 5.1, should it only build 5.1 images as well or still 5.0?

I have no clue what that job is doing nor what entails changing from 5.0 to 5.1, so could you please either you or anyone else that understands the job speak up? Thanks in advance!

**Comment by svx** [comment]
@gforcada that is a project from @bloodbare :)

The docker other docker images are in https://github.com/plone/plone.docker and these are not using our ci setup

**Comment by gforcada** [comment]
@svx thanks for the quick response!

@bloodbare is this job still needed then? Or the official docker images are enough for your purposes?

**Comment by gforcada** [comment]
I accidentally removed it, should it be recreated?
