### ISSUE TITLE
QA tests for firstlevel namespace != 'plone/' broken

### ISSUE THREAD

**Issue by jensens** [plone/jenkins.plone.org#160]
see https://github.com/plone/plonetheme.barceloneta/pull/90#commitcomment-16523589

**Comment by gforcada** [comment]
I can not see the comment you linked, do you care to explain a bit more?

**Comment by jensens** [comment]
It seems the qa check depends the code to be in a subdirectory "plone/" and does not work for other subdirectores, like "plonetheme/".

looks like the comments are not very sticky in github...

**Comment by gforcada** [comment]
@jensens where do you see that? Maybe I'm just too blind/busy but I see http://jenkins.plone.org/view/Pkgs/job/package-plonetheme.barceloneta/ being green...

**Comment by jensens** [comment]
indeed, but the now gone comment included a traceback complaining it cant find a directory 'plone/' or alike.

**Comment by gforcada** [comment]
oh, that one was probably old. I already fixed that last week or so ago: https://github.com/plone/jenkins.plone.org/blob/master/jobs.yml#L214

**Comment by jensens** [comment]
sorry for the tempest in a teacup
