### ISSUE TITLE
Have dedicated Plone job, testing if buildout still works with latest setuptools version.

### ISSUE THREAD

**Issue by do3cc** [plone/jenkins.plone.org#161]
If that job would post to twitter, I'd follow that bot ;-)

**Comment by tisto** [comment]
@do3cc not a bad idea. Open another issue. :)

**Comment by tisto** [comment]
+1

**Comment by gforcada** [comment]
That should be fairly trivial to do... the twitter part is another story, but it would be a good idea that *some* jobs report to twitter as well...

**Comment by gforcada** [comment]
There you go: http://jenkins.plone.org/view/QA/job/qa-setuptools/

Just running ``bin/buildout`` is enough? Or it has to run all the tests as well?
