### ISSUE TITLE
Have some bots use the twitter plugin to tweet build failures

### ISSUE THREAD

**Issue by do3cc** [plone/jenkins.plone.org#162]
https://wiki.jenkins-ci.org/display/JENKINS/Twitter+Plugin

I would not follow a twitter bot for plone5, for this I have ccmenu. But I would follow the twitter bot for #161 Because that affects me much more often directly. Even if only because I look at incoming buildout bugs.

**Comment by gforcada** [comment]
Bad news :-( I installed the plugin, configured it with a twitter user, but it does not work :-/

Seems that the plugin is broken/unmaintained https://issues.jenkins-ci.org/browse/JENKINS/component/15584/?selectedTab=com.atlassian.jira.jira-projects-plugin:component-summary-panel

We can of course cook our own twitter connector...

**Comment by gforcada** [comment]
If anyone steps up, that's fine, until then, I prefer to close it to not give false expectations.
