### ISSUE TITLE
Node3 is offline.

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#163]
http://jenkins.plone.org/computer/Node3/

**Comment by svx** [comment]
node 3 is not offline, I can ping the node and the monitor interface is telling me that the node is online, so the node is at least not offline
![node3-ping](https://cloud.githubusercontent.com/assets/358860/13912654/c8441996-ef3f-11e5-9ce3-7c1dc6c9d5c3.png)

**Comment by tisto** [comment]
Yep. I can ssh into the machine. Seems Jenkins master is the problem...

**Comment by tisto** [comment]
Node3 is online again. No idea what went wrong...
