### ISSUE TITLE
Problems on Node 2

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#165]
Several Jenkins jobs are now failing fast on node 2.
- http://jenkins.plone.org/job/plone-4.3-python-2.7/1343/ plus the two after it (two commits by me, plus a manual rebuild by me).
- http://jenkins.plone.org/job/pull-request-5.0/1126/ (also by me)

Relevant part of the console log seems this, taken from the first 4.3 one, but looks similar in the others:

```
vfb starting$ /usr/bin/Xvfb :3 -screen 0 1024x768x24 -fbdir /home/jenkins/xvfb-1343-119003529201829301.fbdir
(EE) 
Fatal server error:
(EE) Server is already active for display 3
	If this server is no longer running, remove /tmp/.X3-lock
	and start again.
(EE) 
unlink: No such file or directory
unlink  failed, Invalid argument
ERROR: Xvfb failed to start, consult the lines above for errors
```

**Comment by mauritsvanrees** [comment]
Well, http://jenkins.plone.org/job/plone-4.3-python-2.7/1346/ is being executed on node 2 now and looks fine.

**Comment by tisto** [comment]
There was a xvfb process running on node2. The display numbers are assigned randomly, sometimes it might work, sometimes not. I killed the process so there shouldn't be any problems...

**Comment by mauritsvanrees** [comment]
Thanks.
