### ISSUE TITLE
jenkins.plone.org is offline

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#167]
Will look into it right away...

**Comment by tisto** [comment]
Ok, Jenkins is back online.

**Comment by gforcada** [comment]
I was user updating mr.roboto yesterday but did not change anything else...
Do you know what was it?
El dia 28/04/2016 9:00, "Timo Stollenwerk" <notifications@github.com> va
escriure:

**Comment by tisto** [comment]
Yeah. I ran an dist-upgrade and that installed Jenkins 2. I had to restart Jenkins to make that work again... :)

See #168.

**Comment by svx** [comment]
I will put this here as a reminder :)

You should be careful with dist-upgrade on production machines, always check before you run it

For dist-upgrades, you can use the --dry-run with sudo apt-get dist-upgrade to simulate running this command without actually performing the upgrade.

 

> -s, --simulate, --just-print, --dry-run, --recon, --no-act
>        No action; perform a simulation of events that would occur but do not actually change the
>        system. Configuration Item: APT::Get::Simulate.
> 
>        Simulate prints out a series of lines each one representing a dpkg operation, Configure (Conf),
>        Remove (Remv), Unpack (Inst). Square brackets indicate broken packages with and empty set of
>        square brackets meaning breaks that are of no consequence (rare).



**apt-get update** updates the list of available packages and their versions, but it does not install or upgrade any packages.

**apt-get upgrade** actually installs newer versions of the packages you have. After updating the lists, the package manager knows about available updates for the software you have installed. This is why you first want to update.

**apt-get dist-upgrade**, in addition to performing the function of apt-get upgrade, also intelligently handles changing dependencies with new versions of packages and will attempt to upgrade the most important packages at the expense of less important ones if necessary. Thus, the apt-get dist-upgrade command may actually remove some packages in rare but necessary instances.
