### ISSUE TITLE
Are we using the stable debian-stable for Jenkins?

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#168]
@gforcada is it possible that we are not using the stable versions of Jenkins?

http://pkg.jenkins-ci.org/debian-stable/

I ran a dist-upgrade on the master server and ended up with having Jenkins 2.0. As far as I can see everything still works. Though, for the future we should switch to "debian-stable" as soon as Jenkins 2.0 is available there...

**Comment by gforcada** [comment]
@tisto I'm not sure which version of ansible-jenkins are we using right now, but it seems to be using something stable: https://github.com/ICTO/ansible-jenkins/blob/development/tasks/jenkins.yml#L18

Sorry didn't look deeper, I will try to look at it at night.

**Comment by gforcada** [comment]
We will be using this one as soon as we redeploy master. The changes on the ansible playbooks are done.

@tisto will you have some time early next month to do a quick hangout about the servers? Maybe @tdesvenain would join as well?

**Comment by gforcada** [comment]
We use the stable channel from jenkins itself.
