### ISSUE TITLE
Jenkins on 5.1 fails due to setuptools redirect problem

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#169]
The last two 5.1 jobs failed.
http://jenkins.plone.org/job/plone-5.1-python-2.7/322/console says:

```
[plone-5.1-python-2.7] $ /bin/bash /tmp/hudson6037478439391730436.sh
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-19.4.zip
Extracting in /tmp/tmpn1Utau
Traceback (most recent call last):
  File "bootstrap.py", line 98, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 175, in use_setuptools
  File "<string>", line 126, in _do_download
  File "<string>", line 66, in _build_egg
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "<string>", line 105, in archive_context
  File "<string>", line 89, in __new__
  File "/usr/lib/python2.7/zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: '/tmp/tmpeYgEMn/setuptools-19.4.zip'
/tmp/hudson6037478439391730436.sh: line 5: bin/buildout: No such file or directory
/tmp/hudson6037478439391730436.sh: line 6: bin/alltests: No such file or directory
```

When I download the setuptools zip with curl, I get a '301 Moved permanently' with in html: "The resource has been moved to https://files.pythonhosted.org/packages/source/s/setuptools/setuptools-19.4.zip; you should be redirected automatically."

The 5.0 pull request job I just started has the same: http://jenkins.plone.org/job/pull-request-5.0/1145/console
4.3 seems unaffected.

I don't immediately see where this is going wrong. Locally, I can run `python2.7 bootstrap.py --setuptools-version=19.4` just fine.

**Comment by gforcada** [comment]
I was having the same on our own project. I think updating to the latest bootstrap.py helps (on our local project I fixed that by having a local setuptools egg and ez_setup.py)

**Comment by gforcada** [comment]
Let's see if https://github.com/plone/buildout.coredev/pull/209 fixes it.

**Comment by gforcada** [comment]
So no, is not enough :-(

**Comment by mauritsvanrees** [comment]
The script does this:
```
python /tmp/hudson7484476214927982015.py
...
/bin/bash /tmp/hudson3862100039862524473.sh
```

Probably autogenerated code. The last one is where it fails. Do you know where this is done? I don't see such code in my jenkins.plone.org checkout.

**Comment by gforcada** [comment]
That's the scripts that jenkins runs, but the problem is still this one I think: https://github.com/pypa/setuptools/issues/568

**Comment by gforcada** [comment]
It's related to setuptools at the end, the latest version 21.0 removed ez_setup.py from itself http://pythonhosted.org/setuptools/history.html#id1 so the combination of bootstrap+ez_setup+download setuptools fails somewhere due to that...

**Comment by gforcada** [comment]
Next try on the pull request works: http://jenkins.plone.org/job/pull-request-5.1/177

**Comment by mauritsvanrees** [comment]
You say it works? I still see the same error on that link.

**Comment by mauritsvanrees** [comment]
I don't think the removal of `ez_setup.py` from setuptools 21 is the problem, because we are using setuptools 19.4. But there may be some subtlety that makes it involved after all.

**Comment by mauritsvanrees** [comment]
Ah, you mean http://jenkins.plone.org/job/pull-request-5.1/178/console which *is* working. Cool.
