### ISSUE TITLE
Update python version on master

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#170]
mr.roboto just gained a functionality to check if a pull request is adding a changelog. For that it downloads the pull request diff and analyzes it.

Unfortunately github redirects to a domain that gives an SSL error on python 2.7.6.

[Some](http://mbless.de/blog/2016/01/09/upgrade-to-python-2711-on-ubuntu-1404-lts.html) point to compile and install your own python version and use it in a virtual environment. We could also use the [deadsnakes](https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes-python2.7) ubuntu PPA, although some warn against it (changing the system python *might* not be the best idea ever.

I would go for the deadsnakes as the "system" as it's just too much trouble setting all that up on ansible (yeah I'm lazy :-)

**Comment by tisto** [comment]
I've been there and struggled with deadsnakes. Ended up with compiling my own python version. In the end it will be more work if you would try it I guess...at least that was my experience some time ago...

**Comment by gforcada** [comment]
By now, even more lazily, I disabled verifying the SSL certificate as a quick fix. I will see if I have time to work on it.

**Comment by gforcada** [comment]
Time to shake the laziness, we not only need a newer python 2.7 version but a 3.5 one as well (current ubuntu version only ships with 3.4).

We need 2.7.x for the reason stated on the first comment and 3.5 not only to start testing more and more plone packages but specially to integrate work done at the barceloneta sprint that was testing against python 3.5.

I will give it a go.

**Comment by gforcada** [comment]
I created an ansible role to install python 2.6, 2.7 and even 3.5 https://galaxy.ansible.com/gforcada/compile-python

I will give it a try first with mr.roboto and then with workers and master.

**Comment by gforcada** [comment]
Fixed with https://github.com/plone/jenkins.plone.org/commit/039604ee058c83c292f2b35c3c951914185e58a1
