### ISSUE TITLE
Changelog verifier wrongly complains when CHANGES.rst is missing

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#171]
See for example https://github.com/plone/Products.TinyMCE/pull/143
The changelog verifier claims that no changelog entry was found, but this is wrong.
Problem is probably that this package does not have a `CHANGES.rst` but a `HISTORY.rst`.

Some things that could work:
- Do not do the check when `CHANGES.rst` is missing. Danger is then that the checker says everything is fine even though a changelog entry is *really* missing.
- Check more files: `CHANGES.rst` and `HISTORY.rst`, same but with `txt`, and also in the `docs` or `doc` directory. Or maybe anywhere in the package. See https://github.com/zestsoftware/zest.releaser/blob/9c2ff983e14ce6eae356ace943052bf7d1265155/zest/releaser/vcs.py#L114

**Comment by gforcada** [comment]
It should do so already: https://github.com/plone/mr.roboto/blob/master/src/mr.roboto/src/mr/roboto/subscriber.py#L20

I will take a closer look later today

**Comment by gforcada** [comment]
Should be fixed...
