### ISSUE TITLE
Two CMF builds have been running for 13 and 14 hours

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#177]
The CMF27/34 builds are stuck trying to checkout from svn.zope.org.
Looks like svn.zope.org is unresponsive, at least I don't get an answer when doing `svn ls svn://svn.zope.org/repos/main/CMF/trunk`.
It seems best if someone kills these current builds.

Also, it seems wrong to check out from subversion when everything from CMF is on github, but that is another discussion. The job ran fine a week ago.

**Comment by gforcada** [comment]
@mauritsvanrees thanks for noticing, they are cleaned already. I will check which buildout they are using...

**Comment by gforcada** [comment]
There was a workspace still around on one of our nodes, so I copied its buildout configuration (funnily enough, all sources where pointing to github, while this buildout was still on svn...) and made this: https://github.com/plone/buildout.coredev/commit/0c95439da796f508656d248b426c65f44f35b363

I'm updating jenkins.plone.org jobs and testing them.
