### ISSUE TITLE
The Plone Contributor Agreement check fails if some one was using the Github Editor

### ISSUE THREAD

**Issue by MrTango** [plone/jenkins.plone.org#178]
Hi,

i was using the Github TTW Editor to edit the history.txt of a repo and the Plone Contributor Agreement check fails now, because it sees the user web-flow instead of me. But when i loook into the commits, there is  still my username listed.

https://github.com/plone/ansible.plone_server/pull/85

**Comment by gforcada** [comment]
That's interesting: https://api.github.com/repos/plone/ansible.plone_server/pulls/85/commits

Indeed there's a commiter named GitHub with a noreply@github.com as email.

Whitelisting that user is probably enough.

Thanks for reporting it!

**Comment by MrTango** [comment]
But we should check if this does not open the door for TTW editing for all users ;)

**Comment by gforcada** [comment]
No that would be fine as mr.roboto checks **both** author and committer and complains at any of them not being part of Plone organization. But good point nonetheless.
