### ISSUE TITLE
Can't load the profile (firefox)

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#180]
We've got a newer Firefox on Jenkins: jay!!!

But the robot tests now say:

```
Setup failed:
WebDriverException: Message: Can't load the profile. Profile Dir: %s
If you specified a log_file in the FirefoxBinary constructor, check it for details.
```

See also https://github.com/plone/jenkins.plone.org/issues/179 and https://github.com/plone/plone.jenkins_node/pull/8

**Comment by gforcada** [comment]
Maybe we need to update selenium (and related distributions) just like 5.1 branch (on buildout.coredev) on 5.0 and 4.3 branches?

**Comment by mauritsvanrees** [comment]
Strange is:
- 4.3 works
- 5.0 and 5.1 *robot tests* completely fail to startup, finding no browser. No wait, 5.1 almost goes fine. I thought that one was utterly broken too.
- 5.0 and 5.1 *pull requests* go almost fine, except the robot tests for scenario 'Location query' and sometimes 'After you fix linked page no longer show warning'. For example http://jenkins.plone.org/job/pull-request-5.1/396/testReport/

**Comment by mauritsvanrees** [comment]
pull request for 5.0: https://github.com/plone/buildout.coredev/pull/227

**Comment by mauritsvanrees** [comment]
More strangeness:
This 5.0 pull request job on Node 4 almost worked, just one test failure: http://jenkins.plone.org/job/pull-request-5.0/1252/injectedEnvVars/

But this 5.0 pull request job with the same pull request (update selenium/robot) plus one extra (backport robot test fix in CMFPlone) completely fails again: `Can't load the profile. Profile Dir: %s`. The test run is not finished yet, so you cannot see the environment variables. But on the front page you can see that this job is being run on the same Node 4. See http://jenkins.plone.org/job/pull-request-5.0/1253/

So on the same node one jobs is (almost) fine and the other completely fails to find a browser.
I do remember that this sometimes happened with the older firefox too, that you saw 'cannot open browser' or something like that. So maybe this is an old problem.

**Comment by mauritsvanrees** [comment]
This is still a problem.
Strangely, it seems 4.3 and 5.1 are behaving fine, but 5.0 not: both the pull request and the robot test jobs fail.

Well, I'll go ahead and merge two related pull requests that bring the 5.0 coredev versions (https://github.com/plone/buildout.coredev/pull/227) and CMFPlone robot tests (https://github.com/plone/Products.CMFPlone/pull/1651) in line with how it is on 5.1.
Sorry for barging in like this, but I think any remaining problems are easier to fix when 5.0 is as much alike 5.1 as possible.

**Comment by mauritsvanrees** [comment]
Jay! For the moment it seems to work. Both these jobs have correctly finished the first robot tests:
- http://jenkins.plone.org/job/plone-5.0-python-2.7-robot/4755/console (node 1)
- http://jenkins.plone.org/job/plone-5.0-python-2.7-robot/4756/console (node 3)

This older one is still busy, but failing:
- http://jenkins.plone.org/job/plone-5.0-python-2.7-robot/4754/console (node 3)

**Comment by mauritsvanrees** [comment]
All is well now. I have not seen firefox problems anymore. Thanks!

Note: Firefox 47.0.1 is out with a fix for the web driver, so that sounds like it might be usable for us. But when I update my Firefox version locally and run a robot test, the browser opens without error but the window just stays open and nothing happens. After a while the robot test quits and says basically the same as above: `WebDriverException: Message: Can't load the profile. Profile Dir: /var/folders/.........../webdriver-py-profilecopy`. Possibly this might be fixed with a newer selenium version or whatever.

Anyway, Firefox 46 seems to be doing fine on jenkins with 4.3, 5.0 and 5.1.
Closing.

**Comment by gforcada** [comment]
@mauritsvanrees thanks for looking over it! :bow:
