### ISSUE TITLE
Remove broken PasswordResetTool egg

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#181]
We have a broken egg again, due to two buildouts that ran simultaneously.

```
ImportError: No module named PasswordResetTool
```

http://jenkins.plone.org/job/pull-request-5.1/397/injectedEnvVars/

This is on Node 3.

**Comment by gforcada** [comment]
Removed all of them, run again

**Comment by gforcada** [comment]
Thanks for noticing **and** reporting! :+1:

**Comment by mauritsvanrees** [comment]
Thanks!
