### ISSUE TITLE
Code analysis jobs hanging

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#182]
There are four code analysis jobs running that keep hanging. the first three on node 1, the last on node 4.

General problem for all is:

```
Version and requirements information containing transaction:
  [versions] constraint on transaction: 1.4.4
  Requirement of ZODB3>=3.9: transaction>=1.1.0
  Requirement of Zope2>=2.12.1: transaction
  Requirement of transaction>=1.1.0: zope.interface
  Requirement of Products.StandardCacheManagers: transaction
  Requirement of zope.sendmail: transaction
  Requirement of ZODB3: transaction>=1.1.0
  Requirement of Products.ZCTextIndex: transaction
  Requirement of AccessControl>=2.13.2: transaction
  Requirement of Zope2>=2.13.0a1: transaction
  Requirement of AccessControl: transaction
  Requirement of ZODB3>=3.9.0: transaction>=1.1.0
  Requirement of Zope2>=2.13.0dev: transaction
  Requirement of Zope2: transaction
  Requirement of ZODB: transaction>=1.5.0
While:
  Installing.
  Getting section packages.
  Initializing section packages.
  Getting option packages:eggs.
  Getting section instance.
  Initializing section instance.
  Installing recipe plone.recipe.zope2instance.
Error: The requirement ('transaction>=1.5.0') is not allowed by your
[versions] constraint (1.4.4)
```

On node one, all have this problem:

```
No space left on device
```

- First one: http://jenkins.plone.org/job/qa-code-analysis/244/console
- http://jenkins.plone.org/job/qa-code-analysis/245/console has as last line: `Report Violations is waiting for a checkpoint on Code analysis #244`
- http://jenkins.plone.org/job/qa-code-analysis/246/console has as last line: `Report Violations is waiting for a checkpoint on Code analysis #245`
- http://jenkins.plone.org/job/qa-code-analysis/247/console has as last line: `Report Violations is waiting for a checkpoint on Code analysis #246`

So the last three are all waiting on the previous one to finish.

Ah, and each day one new job starts. So we need to:
- Stop all four jobs. (Maybe only the first one and then give the others time to finish after all.)
- Fix the requirement. This is with 'bin/buildout -c experimental/qa.cfg' in coredev 5.1, right? Goes fine locally.

**Comment by mauritsvanrees** [comment]
These have been stopped now. I think @gforcada did that. Thanks!
I wonder if the next regularly started job will behave well, but we'll see.

**Comment by gforcada** [comment]
@mauritsvanrees I have to take a look at why they were hanging... too much work and not feeling too well prevents me from doing that unfortunately :-/
