### ISSUE TITLE
Disk full on Jenkins nodes

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#183]
This job on Node 2 is failing due to disk shortage: http://jenkins.plone.org/job/pull-request-5.1/402/console

Via #182: node 1 is full.
Might need to check 3 and 4 for good measure.

**Comment by gforcada** [comment]
All of them cleaned again. I guess some jobs keep adding **lots** of content to /tmp and not cleaning up afterwards.

**Comment by gforcada** [comment]
Thanks for reporting!!
