### ISSUE TITLE
GithubAuthenticationToken error on Jenkins

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#184]
I am getting this on the last two 5.0 pull requests:

```
ERROR: No Xvfb installations defined, please define one in the configuration.
```

Also:

```
ERROR: Could not send email as a part of the post-build publishers.
java.lang.ClassCastException: org.acegisecurity.providers.UsernamePasswordAuthenticationToken cannot be cast to org.jenkinsci.plugins.GithubAuthenticationToken
```

See http://jenkins.plone.org/job/pull-request-5.0/1290/console
More jobs have this currently. These were on Node 1.

But this one failed with the github authentication token error on Node 2: http://jenkins.plone.org/job/plone-5.0-python-2.7-at/4902/console

**Comment by gforcada** [comment]
@mauritsvanrees thanks for reporting all the issues, I'm rather busy lately and barely keep an eye on jenkins.plone.org

The xfvb issue should be mostly solved, there may be some jobs to be fixed, but it's too late to go through all of them :-/

For the github one I need to be fully awake to connect all the dots, I will try to look tomorrow (today) morning.

**Comment by gforcada** [comment]
I think I fixed it (just updating the jenkins plugins). Please re-open if it happens again.
