### ISSUE TITLE
Failure on new node 5 fail: no module named github

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#191]
Woohoo, I notice node 5 for the first time today. Great!

But the 5.1 pull request job fails (maybe others too):

```
[pull-request-5.1] $ python /tmp/hudson4442027151287043745.py
Traceback (most recent call last):
  File "/tmp/hudson4442027151287043745.py", line 2, in <module>
    from github import Github
ImportError: No module named github
Build step 'Execute Python script' marked build as failure
```

This happened for the last three pull requests, which were all started by me. They are for the same [plone.api pull request](https://github.com/plone/plone.api/pull/337), which I restarted to see if it was a glitch:
- http://jenkins.plone.org/job/pull-request-5.1/993/
- http://jenkins.plone.org/job/pull-request-5.1/994/
- http://jenkins.plone.org/job/pull-request-5.1/995/

**Comment by gforcada** [comment]
uh, sorry that's right, I wasn't finished but I wanted to keep trying it. I will disable on the meantime!

**Comment by gforcada** [comment]
Disabled!
