### ISSUE TITLE
No space left on Node 3

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#200]
See http://jenkins.plone.org/job/pull-request-4.3/558/console

**Comment by gforcada** [comment]
I'm cleaning it a bit more but it's already below 95%

**Comment by gforcada** [comment]
Left if at 80%, node1, node2 and node3 anyway will be removed eventually as they are still on rackspace and we wanted to quit using rackspace for that

**Comment by tkimnguyen** [comment]
I'm pestering the Wildcard sysadmins to find out when they can give you the new server. It's built but there is some networking config remaining.

**Comment by gforcada** [comment]
@tkimnguyen let's sort that out during the PLOG 👍
