### ISSUE TITLE
Pull request jobs do not pick changes up

### ISSUE THREAD

**Issue by Rotonen** [plone/jenkins.plone.org#205]
I tried to make a pull request to `plone.app.versioningbehavior` and the change from the pull request does not seem to be picked up by the pull request jobs on `jenkins.plone.org`.

plone/plone.app.versioningbehavior/pull/34
http://jenkins.plone.org/job/pull-request-5.0/63/
http://jenkins.plone.org/job/pull-request-5.1/140/

User error or what's up here?

**Comment by gforcada** [comment]
@Rotonen I see that the pull requests jobs were started (manually, they don't start automatically) and did run. How do you see that they did not pick your changes?

**Comment by gforcada** [comment]
On the 5.0 job: http://jenkins.plone.org/job/pull-request-5.0 as it is still the last run (right now), I see that p.a.versioningbehavior is on checkouts.cfg and that on sources.cfg it points to your branch: 
```
plone.app.versioningbehavior = git git://github.com/plone/plone.app.versioningbehavior.git branch=roto_add_missing_ttw_form
```

Is there anything else missing?

**Comment by Rotonen** [comment]
@gforcada so user error, thank you for clearing up how this works.

I was expecting

http://jenkins.plone.org/job/pull-request-5.0/63/changes
http://jenkins.plone.org/job/pull-request-5.1/140/changes

to have picked up the changes from the pull request and display the changelog entry / changeset.

**Comment by gforcada** [comment]
@Rotonen no, unfortunately so far no one was asking for that, so myself, the one that wrote the pull request jobs, never though of that 😓
