### ISSUE TITLE
Report from plone.versioncheck

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#207]
*Coming over from https://github.com/plone/buildout.coredev/issues/255*

Create a jenkins job that runs plone.versioncheck once per week.

It needs a buildout.coredev 5.1 checkout to run the following command:

``./bin/versioncheck -prb > dependencies.html``

Archive the result so it can be easily checked.

**Comment by jensens** [comment]
implemented with GH actions for now, it is sufficient. https://github.com/plone/buildout.coredev/actions/workflows/versioncheck.yml
