### ISSUE TITLE
Update http://jenkins.plone.org/py3/

### ISSUE THREAD

**Issue by pbauer** [plone/jenkins.plone.org#212]
can we get a freshly built version of that amazing site?

**Comment by pbauer** [comment]
Also it would be nice to have documentation how to update that on our own :-D

**Comment by gforcada** [comment]
It is actually, although a bit obfuscated, but hey, until today nobody asked 😛 

Code is here: https://github.com/collective/ztk-py3-status
Docs are here: https://github.com/collective/ztk-py3-status/blob/master/package_delta.py
To update it on jenkins.plone.org we could either add a cron task or keep it as it is now to update it manually.

**Comment by gforcada** [comment]
@plone/framework-team for those of you interested (or anyone else actually) I updated it again by switching to 5.2 branch, see https://github.com/collective/ztk-py3-status/commit/6c39f02e53a4cc4883df764e5360a6420faaaf50 for the packages added/removed. We have 10 dependencies less 🎉
