### ISSUE TITLE
IOError on node 4: disk full

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#218]
`[Errno 28] No space left on device`
See https://jenkins.plone.org/job/pull-request-5.2/386/, which ran a PR for https://github.com/plone/Products.CMFPlone/pull/2299.

Possibly related is https://github.com/plone/buildout.coredev/pull/407, which can easily have led to more hard disk space being used.

**Comment by mauritsvanrees** [comment]
The last five jobs for 5.1 robot tests (1023-1027) have failed too, which may or may not be related.
https://jenkins.plone.org/job/plone-5.1-python-2.7-robot/1027/ strangely lists only 18 robot tests as total, although they apparently all passed.
There were all on node 4 as well.

**Comment by mauritsvanrees** [comment]
Okay, [5.1 robot job 1028](https://jenkins.plone.org/job/plone-5.1-python-2.7-robot/1028/) is green again, as it ran on Node 1.

**Comment by gforcada** [comment]
Thanks for noticing, I cleared up `/tmp`:

`/dev/sda1        42G   23G   17G  58% /`

**Comment by mauritsvanrees** [comment]
Thanks! 👍
