### ISSUE TITLE
Jenkins VM donation

### ISSUE THREAD

**Issue by senner** [plone/jenkins.plone.org#22]
All,
We'd be happy to donate some CPU power.  We have a cluster here that'd be perfect for it, the caveat is that it does get rebooted from time to time as we are making updates/changes in the configurations and we'll have to do the jenkins launch slave agent headlessly option as there is no inbound access as that IP will be changing.  We can give out a bunch of CPU cores and storage though.

We'd actually be able to do a perceus boot via a stateless VNFS (which is an ubuntu system) as well if that would be of interest.  That could run in VM or on bare metal.

**Comment by gforcada** [comment]
Closing as most probably that's already old... feel free to reopen.
