### ISSUE TITLE
ploneorg theme preview is being used?

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#220]
@sneridagh there is a jenkins job that builds plone.org's theme on a daily basis (I just changed it to be on a weekly basis).

It is broken right now and for many months already. Is that actually being used at all? should it be kept?

**Comment by sneridagh** [comment]
I guess you can drop it, maybe we set that up while developing it.

**Comment by gforcada** [comment]
ok, I will do so, thanks for answering!!
