### ISSUE TITLE
Clone buildout-coredev with depth 1 and specific branch

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#222]
I noticed failures today on Jenkins with Plone 5.0 which were caused by a failed clone of coredev.
For example [this one](https://jenkins.plone.org/job/plone-5.0-python-2.7/646/console). It is actually a timeout, when you look at the top of this info:

```
Cloning the remote Git repository
Cloning repository git://github.com/plone/buildout.coredev.git
 > git init /home/jenkins/workspace/plone-5.0-python-2.7 # timeout=10
Fetching upstream changes from git://github.com/plone/buildout.coredev.git
 > git --version # timeout=10
 > git fetch --tags --progress git://github.com/plone/buildout.coredev.git +refs/heads/*:refs/remotes/origin/*
ERROR: Timeout after 10 minutes
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: 
Command "git fetch --tags --progress git://github.com/plone/buildout.coredev.git +refs/heads/*:refs/remotes/origin/*" 
returned status code 143:
stdout: 
stderr: remote: Counting objects: 74829, done.        
remote: Compressing objects:   0% (1/260)
...
Receiving objects:  60% (44963/74829), 52.50 MiB | 65.00 KiB/s   
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1996)
...
		at hudson.model.Run.execute(Run.java:1727)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
ERROR: Error cloning remote repo 'origin'
```

I have seen that before, and usually restarted the failed job, and then all was fine.

Here it got about 50 MB of data and then quit. So much data should not be necessary.

I think we have have tried specifying a depth, but feared that this depth might not contain enough commits to checkout a specific branch.  But that seems no problem.  I tried it out locally with three different commands. Here I try to get the 5.0 branch in three ways:

**Standard full clone:**

```
$ time git clone git@github.com:plone/buildout.coredev standard
Cloning into 'standard'...
remote: Counting objects: 74829, done.
remote: Compressing objects: 100% (260/260), done.
remote: Total 74829 (delta 189), reused 67 (delta 33), pack-reused 74535
Receiving objects: 100% (74829/74829), 147.63 MiB | 853.00 KiB/s, done.
Resolving deltas: 100% (48166/48166), done.

real	3m6.000s
user	0m9.089s
sys	0m3.782s
$ cd standard
$ git co 5.0
Branch '5.0' set up to track remote branch '5.0' from 'origin' by rebasing.
Switched to a new branch '5.0'
$ cd -
$ du -sh standard/.git
159M	standard/.git
```

**Clone all commits of a single branch:**

```
$ time git clone --single-branch --branch=5.0 git@github.com:plone/buildout.coredev 5.0-branch
Cloning into '5.0-branch'...
remote: Counting objects: 45018, done.
remote: Compressing objects: 100% (625/625), done.
remote: Total 45018 (delta 2398), reused 2134 (delta 2127), pack-reused 42266
Receiving objects: 100% (45018/45018), 138.46 MiB | 2.26 MiB/s, done.
Resolving deltas: 100% (28406/28406), done.

real	1m3.840s
user	0m6.015s
sys	0m1.976s
$ du -sh 5.0-branch/.git
145M	5.0-branch/.git
```

This is three times as fast, but I wonder if that is random, because we get almost the same amount of data.

**Clone only the last commit of a single branch:**

```
$ time git clone --depth=1 --branch=5.0 git@github.com:plone/buildout.coredev 5.0-tip
Cloning into '5.0-tip'...
remote: Counting objects: 86, done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 86 (delta 3), reused 24 (delta 0), pack-reused 0
Receiving objects: 100% (86/86), 139.56 KiB | 1.44 MiB/s, done.
Resolving deltas: 100% (3/3), done.

real	0m1.834s
user	0m0.041s
sys	0m0.057s
$ du -sh 5.0-tip/.git
236K	5.0-tip/.git
```

The first two get around 150 MB of data, the last one with depth 1 gets not even 1 percent of that!

**Result:**

Do we really get the same end result as a checkout? Let's remove the `.git` directories and compare the three clones:

```
maurits@MauritsBook:tmp $ rm -rf standard/.git 5.0*/.git
maurits@MauritsBook:tmp $ du -sh standard 5.0-branch 5.0-tip 
516K	standard
516K	5.0-branch
516K	5.0-tip
maurits@MauritsBook:tmp $ diff -r standard 5.0-branch
maurits@MauritsBook:tmp $ diff -r standard 5.0-tip
```

_No difference!_

So it should be safe to us the third, much less data-intensive method, where the trick is to specify both a depth and a branch:

```
git clone --depth=1 --branch=5.0 git@github.com:plone/buildout.coredev
```

Note that according to `git clone --help`, the depth argument implies `--single-branch`. Usually that will be `master`, or in case of coredev currently `5.1`. But when you specify the specific `--branch`, it will work.

So I propose to change that. Github will thank us. :-) I don't quite see where in the code this is done though.

**Comment by mauritsvanrees** [comment]
BTW, the Plone 5.0 Python 2.7 job has failed three times in a row now because of this, starting from https://jenkins.plone.org/job/plone-5.0-python-2.7/645/, followed by two restarts from me, all on Node 4.

For the Archetypes and robot tests this failed one time, and I restarted them successfully.

**Comment by gforcada** [comment]
I'm on vacations, but I think that the original clone, not the ones from buildout that ate already cloning a few commits, can not be reduced as jenkinsvis using it to compare

**Comment by gforcada** [comment]
Sorry, I clicked on the wrong button... I meant to say that the main clone might not be made it work that way due to Jenkins, I will double check it when I'm back from vacations 😃

**Comment by gforcada** [comment]
@mauritsvanrees I finally (oops :sweat_smile: ) had a look at it, and indeed, one can define if a shallow clone should be used and how much history to fetch.

I set it to 50 commits, I hope is enough.
