### ISSUE TITLE
build permission gone?

### ISSUE THREAD

**Issue by jensens** [plone/jenkins.plone.org#223]
At https://jenkins.plone.org/ I no longer can use the blue `Build Now` button. In past it worked for me. I.e. here https://jenkins.plone.org/job/plone-5.1-python-2.7-at/

Having this permission is very handy while merging PR's. Otherwise I have to create dummy-pushes, which is ugly.

**Comment by gforcada** [comment]
No idea what happened, I will have a look when I'm back from vacations. Ping me in z week if I haven't said anything 😃

**Comment by jensens** [comment]
Thanks, enjoy your vacations!

**Comment by jensens** [comment]
Update: I just figured out, the blue Build button on the top does not work. The fat Build Now link on the left does work.

**Comment by gforcada** [comment]
So this is a non issue already :-)

Actually the fat button on top, was a bit misleading, as it was also there on pull request jobs and other parametrized jobs, and on those it never actually worked.
