### ISSUE TITLE
Proposal for Chromium instead of Firefox for Robot Tests

### ISSUE THREAD

**Issue by jensens** [plone/jenkins.plone.org#227]
If it comes to Robot-Tests on Firefox with a lot of JavaScript involved the tests often are unstable. Same tests on Chromium (the OpenSource Google Chrome) are complete stable. Together with my intern we debugged those for quite a while, but it is not obvious what’s going on there. We suppose that there is some timing problem with race condition between the selenium test-driver and the Javascript Engine in some way. But there are too many complex systems involved and so it is very difficult to debug. We got a better understanding of the processes and were able to stabilize the code with out using ``Sleep`` keywords. But under Firefox some test are still just stuck for no obvious reason while chromium works perfect. And this happened several times in different contexts in past. And too many smart people were not able to solve the problems. And too many time was wasted.

So, why don't we use Chromium as our test-browser? 

Installation is pretty simple, since all needed packages are part of Ubuntu 18.04: ``chromium-browser`` and ``chromium-chromedriver``. We just need to expose an environment variable ``ROBOT_BROWSER=chrome`` before starting the tests. That's all.

**Comment by Rotonen** [comment]
Do the current Robot tests pass with Chromium? In my recent experience with the Plone Robot tests, different tests are flaky between Firefox and Chromium.

I'd not oppose giving the axe on 5.2 for any flaky Robot test.

+1 per the `chromedriver` packages being way less of a hassle to install on both Debian and Ubuntu as they just come out of the repotree (but unfortunately they do have a different package name between the distros).

https://packages.debian.org/chromedriver
https://packages.ubuntu.com/chromium-chromedriver

**Comment by tisto** [comment]
We (at kitconcept) switched to using Chrome as default for robot testing quite a while ago. Though, we had problems with chromium and switched the standard Chrome which works well. We had some scalability issue with Chrome/Chromium though. If you call the "Open browser" keyword for every single test the Chrome/Chromium process just dies.

I'd be ok with switching. Though, someone would need to make the tests run/pass on Chrome/Chromium.

The big plus of using Chrome/Chromium is indeed chromedriver which always works if you keep up with the latest version.

**Comment by gforcada** [comment]
I'm on vacations, around the 13th I'm back.

We can first add a parallel job that runs chrome, and once stable enough we can switch.

**Comment by gforcada** [comment]
@jensens the jobs are up :-)

I will prepare the changes for the pull request jobs, but will not push them right now, as I see some tests failing on chrome but not on firefox... if someone can have a look at it...

**Comment by jensens** [comment]
@gforcada Great! I will have a look next week. May you point me to the output at Jenkins, where I can see which are failing?
