### ISSUE TITLE
Use chrome on plip python3 job

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#230]
@pbauer the only jenkins jobs that is still not using chrome is the PLIP job for python 3.

As you are manually (still?) changing it, I left it untouched on purpose. Drop a comment here to know that you are interested in getting that as well and how to proceed.

**Comment by pbauer** [comment]
@gforcada I have not changes that in quite a while. It now runs:

```
#!/bin/bash
sed -i 's/    mr.developer/    mr.developer\ngit-clone-depth = 10/' core.cfg
pip install -r requirements.txt
buildout -c py3.cfg
cat bin/test

return_code="all_right"

export ROBOTSUITE_PREFIX=ONLYROBOT
./bin/test --all --xml -vvv -t ONLYROBOT || return_code=$?
./bin/test --xml -vvv  || return_code=$?

if [ $return_code = "all_right" ]; then
    return_code=$?
fi

# Keep tests return code
exit $return_code

```

Feel free to improve that to use chrome.

**Comment by gforcada** [comment]
That's done already.
