### ISSUE TITLE
Problem accessing /job/pull-request-5.1/. Reason:      Not Found

### ISSUE THREAD

**Issue by agitator** [plone/jenkins.plone.org#250]
jenkins at https://jenkins.plone.org/job/pull-request-5.1/ not available

**Comment by agitator** [comment]
@gforcada @tisto ping?

**Comment by gforcada** [comment]
Seems to be for anonymous users only... when logged in it works :confused:

**Comment by agitator** [comment]
<img width="1257" alt="screenshot 2018-12-12 at 09 07 48" src="https://user-images.githubusercontent.com/365761/49855410-782b9a00-fded-11e8-8dc4-7436833921e4.png">
<img width="1257" alt="screenshot 2018-12-12 at 09 07 57" src="https://user-images.githubusercontent.com/365761/49855412-795cc700-fded-11e8-9d14-90606acd3213.png">

Cannot confirm, just tried with Firefox, Safari and Chrome

**Comment by gforcada** [comment]
I thought that it has to do with the new LTS release I upgrade it to (2.150.1) that has this: https://jenkins.io/redirect/stapler-routing/ but I don't see any messages on the Jenkins logs :confused: 

I'm investigating further :mag:

**Comment by gforcada** [comment]
Yes, there was a plugin (github authentication) that needed an upgrade as well.
