### ISSUE TITLE
No longer test Plone 5.0

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#253]
Plone 5.0.10 has been soft released a while ago and should be officially released really soon.
This should be the last release in the 5.0.x series, so we should stop testing it.
From the top of my head:

- [x] Update mr.roboto to not check if a PR needs to be tested against the coredev 5.0.x branch.
- [x] Remove the Pull Request 5.0 job
- [x] Remove the jobs Plone 5.0 Python 2.7, Archetypes, Robot Framework tests Chrome/Firefox

Anything else?

cc @plone/testing-team @plone/release-team

**Comment by gforcada** [comment]
Can we include, the already long ago disabled, 4.3 on python 2.6? :cherries:

**Comment by gforcada** [comment]
There were some more 5.0 jobs (translations, theme, addons...) but they are gone: https://github.com/plone/jenkins.plone.org/commit/d073fca367676d1694b7f3046d858c459d18bc89

**Comment by mauritsvanrees** [comment]
Thanks!

Yes, 4.3 on Python 2.6 can be removed in my opinion. It is already not visible anymore on the Jenkins homepage.

**Comment by gforcada** [comment]
What should we do with these bugs: https://github.com/plone/Products.CMFPlone/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Plone+5.0.x%22 they were reported against 5.0.x

Can we mass close them with a comment to reopen if they are still a problem on 5.1/5.2? :thinking: @plone/framework-team do we have any policy on that? :thinking: @ebrehault this should be a discussion point for the next meeting?

**Comment by gforcada** [comment]
> Thanks!
> 
> Yes, 4.3 on Python 2.6 can be removed in my opinion. It is already not visible anymore on the Jenkins homepage.

I already removed them :+1:

**Comment by gforcada** [comment]
mr.roboto is also updated, no commits here as it is a setting :smile:
