### ISSUE TITLE
Node 2 problems: Missing Python 3.8, polluted caches

### ISSUE THREAD

**Issue by jensens** [plone/jenkins.plone.org#261]
On Node 2 Python 3.8 is missing in `srv`. I guess this is an Ansible thing to install?

Also, it seems the caches are in need of an reset. For some reason we got an CRC error on one file (Pillow).

/cc @pbauer

**Comment by gforcada** [comment]
When I was installing 3.8 on Node1, Node2 for whichever reason, was not online.

**Comment by gforcada** [comment]
We can change the firefox jobs, to not run on every commit, but on a weekly basis, as they are not that reliable, it does not make sense anyway to run them on every change... we don't do that already for the pull requests jobs, were we only run robot tests on chrome.

**Comment by jensens** [comment]
> Node2 for whichever reason, was not online

I know, after reboot it was stuck in fsck. I now force to it to repair.

> We can change the firefox jobs, to not run on every commit, but on a weekly basis

+1 

Looks also like the jobs-log at the moment tell us to switch the driver to geckodriver?

**Comment by gforcada** [comment]
> Looks also like the jobs-log at the moment tell us to switch the driver to geckodriver?

Where do you see that? :thinking:

**Comment by jensens** [comment]
https://jenkins.plone.org/job/plone-5.2-python-3.8-robot-firefox/2/console
```
...
==============================================================================
Test Controlpanel Navigation                                                  
==============================================================================
Scenario: Enable Folderish Tabs in the Navigation Control Panel       | FAIL |
Setup failed:
WebDriverException: Message: Can't load the profile. Possible firefox version mismatch. You must use GeckoDriver instead for Firefox 48+. Profile Dir: /tmp/tmpsgpfxhb3 If you specified a log_file in the FirefoxBinary constructor, check it for details.
...
```

**Comment by gforcada** [comment]
I will try to have a look at what's wrong there, it was working before :tm:

**Comment by gforcada** [comment]
python 3.8 is on Node 2, the polluted caches and the gecko driver are still to be checked

**Comment by gforcada** [comment]
@jensens were did you see the CRC errors (i.e. the cache problem)? :thinking: providing links is usually a way to get faster responses/actions :+1:

**Comment by jensens** [comment]
Do we need more disk space? Looks like 40GB are not enough anymore?
```
root@tau:/# du -sh *
22G home
...
2.0G    srv
0   sys
8.3G    tmp
3.1G    usr
3.0G    var
```

**Comment by gforcada** [comment]
The more python versions we want to support, the more packages we have to keep on `~/.buildout/eggs` and the more jobs (and their `buildout.coredev` clones we have to keep, etc etc).

So, yes, we do need more space :sweat_smile:

**Comment by gforcada** [comment]
FYI on `Node1` there are `350Gb` available, `40Gb` used so far.

**Comment by gforcada** [comment]
As there were no jobs running, I removed all workspaces from `Node` (which removed `16Gb`) but they will eventually come back, maybe some were old workspaces, but I would consider that a low gain if at all.

**Comment by jensens** [comment]
@gforcada I can provide a fresh machine with 100GB. This one hasn't, for some unknown reason, LVM, so it's difficult to resize. But your setup via Ansible should reduce efforts on your side, right?

**Comment by jensens** [comment]
@gforcada which base system should I install? Latest Ubuntu Server LTS (18.04)?

**Comment by gforcada** [comment]
@jensens yes to both, `Node 1` is using `Ubuntu 18.04.2 LTS`, and as soon as I can ssh, as root, into the VM I just need to fire ansible and wait for hours until it finishes (building 3.6, 3.7 and 3.8 with optimizations takes quite a while...)

**Comment by jensens** [comment]
@gforcada I setup the machine with Ubuntu 18.04.2 LTS, LVM, image on a ZFS zvol with 90GB. Future resizing is no problem. Server has same IP as before, your username is same as here. PW comes on extra channel.

**Comment by gforcada** [comment]
It is being installed as I type, it will take a few hours though, as the compilation does really take a lot of time :sweat_smile:

**Comment by jensens** [comment]
> it will take a few hours though, as the compilation does  really take a lot of time

No, its the core Python tests (`/python -m test.regrtest --pgo -x test_asyncore test_gdb test_multiprocessing test_subprocess`) that are running which are taking ages. Why do you run them at all? And wouldn't [pyenv](https://github.com/pyenv/pyenv) be the better option to install several Python versions?
