### ISSUE TITLE
Disable Firefox tests

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#262]
Almost all Plone [5.2 robot tests for Firefox](https://jenkins.plone.org/job/plone-5.2-python-2.7-robot-firefox/270/robot/) are failing, with all or most tests saying:

```
Setup failed:
WebDriverException: Message: Can't load the profile.
Possible firefox version mismatch.
You must use GeckoDriver instead for Firefox 48+.
Profile Dir: /tmp/tmpz9qTkY
If you specified a log_file in the FirefoxBinary constructor, check it for details.

Also teardown failed:
No browser is open.
```

And somehow this seems to result in the job lasting more than an hour.  On 5.1 the setup still seems okay, and fast enough, though a few tests always fail. These might be fixable, but it is difficult enough to find people willing to improve the robot tests with Chrome.

Maybe we can just disable the Firefox tests? Some options:

- disable all firefox jobs on all Plone versions
- disable all firefox jobs on 5.2
- disable two of the three firefox jobs on 5.2, and keep either Python 2.7 or 3.7.
- Run the Firefox jobs weekly, as @gforcada [suggests here](https://github.com/plone/jenkins.plone.org/issues/261#issuecomment-508716508)

**Comment by tisto** [comment]
my 2c:

- running two browsers in parallel is a lot of effort in the long run
- running the firefox tests weekly will not be any different to not run them at all, nobody will ever care. either run them all the time or never, everything in between won't work

-> disable the firefox tests and only run chrome tests

**Comment by gforcada** [comment]
That's interesting, the geckodriver is supposed to be new enough, someone would have to dig why that happens only for 5.2 but not on the others :confused: 

As for disabling them partially or completely, I would rather keep it

**Comment by mauritsvanrees** [comment]
Strangely, *some* firefox tests *do* pass.

- This [`plone.app.discussion` test](https://jenkins.plone.org/job/plone-5.2-python-3.7-robot-firefox/lastCompletedBuild/robot/report/robot_log.html#s1-s34-t2-k1) **succeeds**, doing `selenium.Open test browser`.
- This [`plone.app.contenttypes` test](https://jenkins.plone.org/job/plone-5.2-python-3.7-robot-firefox/lastCompletedBuild/robot/report/robot_log.html#s1-s32-t1-k1-k2-k1) **fails**, doing `saucelabs.Open SauceLabs test browser` from the `Plone Test Setup`.

So I think the firefox failures are because we try to run them on SauceLabs instead of locally, and this somehow fails. SauceLabs *does* [support Firefox](https://saucelabs.com/platform/supported-browsers-devices).
So the local geckodriver is likely not the problem.

**Comment by mauritsvanrees** [comment]
On 5.1 with Firefox, [opening a saucelabs browser](https://jenkins.plone.org/job/plone-5.1-python-2.7-robot-firefox/108/robot/report/robot_log.html#s1-s1-t1-k1-k1) works fine.
Strange.

**Comment by mauritsvanrees** [comment]
So which versions of Firefox and GeckoDriver do we have?
Is that on the 5.2 jobs different from the 5.1 jobs?

From the [geckodriver changelog](https://searchfox.org/mozilla-central/source/testing/geckodriver/CHANGES.md):

```
0.26.0
------

Note that with this release the minimum recommended Firefox version
has changed to Firefox ≥60.

...

0.21.0 (2018-06-15)
-------------------

Note that with this release of geckodriver the minimum recommended
Firefox and Selenium versions have changed:

  - Firefox 57 (and greater)
  - Selenium 3.11 (and greater)
```

Selenium is at version 3.14 in coredev 5.1, and that works.
Coredev 5.2 is at Selenium version 3.141.0.
Reverting does not help locally.
The [Selenium Python changelog](https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.59/py/CHANGES) does not contain anything that looks related.
(They have a crazy version policy currently. From that changelog: "Bump version to a better approximation of Π"...)

**Comment by gforcada** [comment]
We are supposed to be using FF 63 and geckodriver 0.23, see https://github.com/plone/plone.jenkins_node/blob/master/defaults/main.yml

I will see if I can bump them to newer versions, FF70 might be too new, but the next FF LTS, whichever is, might be a good candidate

**Comment by mauritsvanrees** [comment]
The Firefox tests on Plone 5.2 are still completely broken. On Plone 5.1 the situation is much better, but still 13 out of 116 tests fail.

And we already have trouble enough keeping the Chrome tests running. See for example `plone.app.multilingual` [PR 366](https://github.com/plone/plone.app.multilingual/pull/366) where I try and fail to fix a most-of-the-time-failing test. For the same package I have created PRs to mark this failing test as unstable, but those PRs already give problems, with some PR jobs passing, some failing in other robot tests, and other jobs timing out after three hours.  See https://github.com/plone/plone.app.multilingual/pull/367 and https://github.com/plone/plone.app.multilingual/pull/368.

So can we disable the Firefox tests? We may keep the job configurations, but just don't run the jobs automatically when coredev changes.

Sure it would be nicer to fix the jobs, but there are enough other issues in this tracker that could use attention.

**Comment by mauritsvanrees** [comment]
The Firefox tests seem to have been disabled. Thanks.
