### ISSUE TITLE
Hide Plone 5.0 jobs

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#263]
The [5.0 jobs](https://jenkins.plone.org/job/plone-5.0-python-2.7/) are not run automatically anymore, because 5.0 is no longer being developed.
So can we hide them from the Core tests on the Jenkins homepage?

I guess it is fine if we keep them visible on the [All tab](https://jenkins.plone.org/view/All/). It seems the jobs can still be started, if someone would want.

**Comment by tisto** [comment]
I currently do not have access to the Jenkins UI as an admin. If @gforcada grants me access I could help with this. Apart from that issue I am +1 to remove the 5.0 jobs from the tab.

**Comment by gforcada** [comment]
@mauritsvanrees they are gone from the main view.
