### ISSUE TITLE
Errno 28 No space left on device

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#267]
See [5.1 PR job](https://jenkins.plone.org/job/pull-request-5.1/155/testReport/junit/Products.Archetypes.tests.test_copying/PortalCopyTests/test_clone_portal/)

**Comment by gforcada** [comment]
*/tmp is being cleaned*

**Comment by gforcada** [comment]
```
root@node1:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/md2        408G   49G  339G  13% /
```

And until `339Gb` of tests leftovers are generated, this issue can be closed :sweat_smile: 

/me wonders about tests generating THAT much leftovers...

**Comment by mauritsvanrees** [comment]
Awesome! Thanks. Good to see you active. :-)

**Comment by mauritsvanrees** [comment]
No space left again, see for example this [5.1 job](https://jenkins.plone.org/job/plone-5.1-python-2.7/140/console).

Maybe cleaning up `/tmp` can be added as a regular cronjob?

**Comment by gforcada** [comment]
@mauritsvanrees that's exactly what I did, every day at 5 AM it will clean up it.
