### ISSUE TITLE
Extra node for Alpine City Sprint?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#270]
Would it be possible to temporarily get an extra node to run jobs? That would be helpful for next week's sprint.
I guess for one week the budget would not be a problem. But still someone from the testing team (or admins team?) would need to have time to set it up.

**Comment by gforcada** [comment]
So far it seems I'm the only one that can actually bootstrap that. If I get access to the server (Ubuntu 18.04 would be best, as that's what the current node is using) I can configure it given a day of time ahead.

**Comment by mauritsvanrees** [comment]
@jensens has offered a VM, details in a mail I just sent you.

**Comment by gforcada** [comment]
@mauritsvanrees cool, I have work and home errands to do, but by night I will try to get it set up :+1:

**Comment by ale-rt** [comment]
@gforcada Syslab can also sponsor a VM, can you give me the details on what is needed?

**Comment by gforcada** [comment]
@ale-rt a ubuntu 18.04 VM with root access. That's about it. The more CPUs the better, not so much about RAM (2-3Gb ?), and as much HD as you wish, lately jobs leave LOTS of files around, so 50-100 Gb would be best

**Comment by gforcada** [comment]
@ale-rt if you add  my ssh key https://github.com/gforcada.keys on the server just send me the IP and that would be it :+1:
