### ISSUE TITLE
Jenkins is down

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#273]
https://jenkins.plone.org is down since at least two hours. I get a connection timeout, and a page saying that my browser works and CloudFlare works, but the Jenkins host is down.

**Comment by gforcada** [comment]
Looks like there is something wrong with the server :-/ I can not even ssh into it

**Comment by gforcada** [comment]
I'm trying to get to the hetzner console, but I fail to find the details for that @polyester might you have them? I fail to find an email with those details, if I ever had them :confused:

**Comment by polyester** [comment]
@gforcada I took a look, the hetzner console just said "rebooting", it was stuck there. So did a "power off" "power on" now

**Comment by polyester** [comment]
I'll put those credentials into a place where the AI team can get at them.

**Comment by mauritsvanrees** [comment]
It is up again. Thanks both!

**Comment by mauritsvanrees** [comment]
Reopening. Main Jenkins is working, and Node 1 is working.
But nodes 2, 3 and 4 are down.  Maybe they just need a kick?

cc @jensens and @ale-rt as their names are on two of those nodes.
I think at least one was down much longer (weeks, months), maybe because it was only temporary.

**Comment by ale-rt** [comment]
Node 3 and 4 are back online :)

**Comment by gforcada** [comment]
Thanks all! :clap:
