### ISSUE TITLE
Naked Jenkins

### ISSUE THREAD

**Issue by jensens** [plone/jenkins.plone.org#274]
The left menu looks very naked even when logged in.
![Screenshot from 2020-09-23 18-14-35](https://user-images.githubusercontent.com/157140/94040085-cba38800-fdc8-11ea-9ea0-de24cb5f2d00.png)

**Comment by jensens** [comment]
I can start the jobs using the dropdown
![Screenshot from 2020-09-23 18-16-42](https://user-images.githubusercontent.com/157140/94040245-fdb4ea00-fdc8-11ea-9ac5-4c74ff29f43e.png)

**Comment by jensens** [comment]
Also the single jobs looks very naked on the left - but functions are in dropdown, and working - so probably not a permission issue.
![Screenshot from 2020-09-23 18-17-31](https://user-images.githubusercontent.com/157140/94040332-19b88b80-fdc9-11ea-8203-c282274fc0e3.png)

**Comment by gforcada** [comment]
On the last release of jenkins that I updated to, there was mentioned that a new theme was added/changed. So I disabled our custom theme on top of it, as it was more and more clashing one to the other...

We can add it back and decide what to use.

**Comment by gforcada** [comment]
:thinking: no I was wrong, the custom theme was still enabled...

Now with it disabled completely the sidebar is still as empty as you found it. So it might be a *feature* of the new theme? :shrug:

**Comment by mauritsvanrees** [comment]
I miss the sidebar, and find it a bit clunky to use the dropdowns for this. But if dropping the theme means we are closer to standard Jenkins, then that is good: less customisations means it is easier to upgrade Jenkins.
And I see security fixes in Jenkins almost daily, it seems...

**Comment by mauritsvanrees** [comment]
I like the new font BTW. :-) Looks a bit cleaner.

**Comment by gforcada** [comment]
I think the sidebar was not part of the theme, or not from our custom theme let's say it this way. So it was an upstream decision to remove them :shrug: maybe to try to get more responsive? :thinking: 

One can try the new blueocean view as well, never tried it myself though.

**Comment by gforcada** [comment]
You can actually have a dark version of the UI as well: https://cd.foundation/blog/2020/08/04/introducing-the-jenkins-dark-theme/

Is still alpha (they say) but it looks better than the light one :+1:

**Comment by jensens** [comment]
so, seems all is fine.
