### ISSUE TITLE
For new Plone 6.0 specific PRs there are no links at Github 

### ISSUE THREAD

**Issue by jensens** [plone/jenkins.plone.org#275]
I am not sure if this is mr.roboto or Jenkins, anyway:

If I create a PR i.e. in buildout coredev on the 6.0 branch I would expect at the PRs "checks" section to pop up job links for Python 3.6. to 3.8, but there is nothing. Same is valid for any other repository and Plone 6. I guess the Jenkins config wasn't created after creating the 6.0 branch.

**Comment by mauritsvanrees** [comment]
I think that is for `mr.roboto`, and mostly [this part](https://github.com/plone/mr.roboto/blob/master/src/mr.roboto/src/mr/roboto/subscriber.py#L430-L454)

**Comment by mauritsvanrees** [comment]
Note that the subscriber for 'please run jobs' is also [in there](https://github.com/plone/mr.roboto/blob/master/src/mr.roboto/src/mr/roboto/subscriber.py#L575-L587).

**Comment by jensens** [comment]
Since it gets the values of Plone versions from a Pyramid registry I suppose the 6.0 is just missing in the ini-file of production mrroboto (key: ``py3_versions`` as here for dev: https://github.com/plone/mr.roboto/blob/219dc5ed86f6cb0210e9b2a95eb8538891dae6df/development.ini.sample#L13)

**Comment by mauritsvanrees** [comment]
We have [`WarnTestsNeedToRun`](https://github.com/plone/mr.roboto/blob/master/src/mr.roboto/src/mr/roboto/subscriber.py#L375) which has as [target url](https://github.com/plone/mr.roboto/blob/master/src/mr.roboto/src/mr/roboto/subscriber.py#L378) `https://jenkins.plone.org/job/pull-request-{plone_version}/`. This matches the Jenkins urls for PR jobs of 4.3, 5.1 and 5.2 on Python 2.7.

For Python 3 jobs, we have [`WarnPy3TestsNeedToRun`](https://github.com/plone/mr.roboto/blob/master/src/mr.roboto/src/mr/roboto/subscriber.py#L431) which has as [target url](https://github.com/plone/mr.roboto/blob/master/src/mr.roboto/src/mr/roboto/subscriber.py#L437) `http://jenkins.plone.org/job/pull-request-5.2-{python_version}`.
It also has code do do nothing if [Plone 5.2 is not in the versions](https://github.com/plone/mr.roboto/blob/master/src/mr.roboto/src/mr/roboto/subscriber.py#L443-L445).

So this `WarnPy3TestsNeedToRun` needs to be fixed to handle Plone 6 as well, or possibly have a separate function for Plone 6, or merge this together with its parent function `WarnTestsNeedToRun`.

**Comment by mauritsvanrees** [comment]
If someone makes a PR, is there then also someone who can put this live?

cc @gforcada @plone/ai-team 

Jens and I could both try to make a PR, but I don't think either of us really knows the inner workings of `mr.roboto`, so it is easy to miss places that need to be fixed, or that an `.ini` file on the server needs an update.

**Comment by gforcada** [comment]
Yes, I can put it live, and I have a faint memory of having started to work on that, obviously failed to deliver it.

I read the other day that the @plone/ai-team is having regular meetings, I should get on one of them and share/hand over the jenkins servers.

**Comment by mauritsvanrees** [comment]
Ah, indeed, you made a branch and PR in January: https://github.com/plone/mr.roboto/pull/78

**Comment by jensens** [comment]
Ping @plone/ai-team  - is it possible to get this fixed? I am happy to help if I get some pointers.

**Comment by jensens** [comment]
I think this magically works now? Or is something missing?

**Comment by fredvd** [comment]
This can be closed.  Gill, Maurits and me fixed this in May or June.
