### ISSUE TITLE
Plone 4.3 jobs can be removed

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#276]
Plone 4.3.20 has been released (though the installer still has to be made). This is the final Plone 4 release that we will ever do.
So all Jenkins jobs and config that relate to Plone 4.3 can be removed, also from `mr.roboto`.

I don't mind if it stays longer, and if someone still wants to make a PR for a Plone 4 package and test it on Jenkins, that is fine with me. But if someone wants to clean this up, you have my blessing.

Maybe just move the 4.3 job out of the Core tab for now. I see Plone 5.0 jobs are also still on the 'All' tab.

Same will soon be true for 5.1, but the 5.1.7 release is still pending, so we should definitely wait with cleaning that up.

**Comment by gforcada** [comment]
So I removed from the Core tab the only 4.3 job that was there, the pull request jobs for 4.3 and 5.0.

I can remove them, did not want to rush it.

**Comment by mauritsvanrees** [comment]
Excellent. Thanks!
