### ISSUE TITLE
dx-siteroot plip job on 6.0 branch

### ISSUE THREAD

**Issue by jaroel** [plone/jenkins.plone.org#278]
Hi all,

I changed the origin for the dx-siteroot plip in #277 , and merged that assuming/hoping it would trigger a deploy of jenkins.plone.org. Now it didn't so I'm wondering what the next step would be 👯

**Comment by gforcada** [comment]
Get someone to deploy it for you 🙂 I will try to do it within today/tomorrow. Ping me here again if I haven't done it

**Comment by gforcada** [comment]
Done :tada: https://jenkins.plone.org/view/PLIPs/job/plip-dx-siteroot-3.8/14/
