### ISSUE TITLE
Code analysis pre-commit hook for coredev and collective packages.

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#28]
I created a pre-commit hook for p.a.contenttypes that is automatically installed by buildout and that checks committed code:

https://github.com/plone/plone.app.contenttypes/blob/master/pre-commit-hook.cfg

We should refactor that code into a buildout recipe so it can be used easily by other coredev or collective packages.

**Comment by gforcada** [comment]
Should we instead focus on the per-package jenkins job to actually do that? Instead of trying to make sure that all and every single developer configures his/her laptops correctly we just need to make sure that all packages are QA tested and that they report back to the committer.

**Comment by tisto** [comment]
Done.
