### ISSUE TITLE
Volto translations job is failing

### ISSUE THREAD

**Issue by erral** [plone/jenkins.plone.org#295]
I can't find where the volto translations script is, but it is failing because of https vs. git clone that was already fixed in some jobs.

Can someone look at it @plone/ai-team ?

https://jenkins.plone.org/view/Translations/job/Volto%20translations/lastFailedBuild/console

**Comment by mauritsvanrees** [comment]
I don't see it in the Jenkins repository code, so maybe this job was added manually.
I logged in on the Jenkins UI and fixed the repo url and now it works. Latest results:

```
Messages: 668

100% - EspaÃ±ol (es)
100% - Basque (eu)
 98% - Catalan (ca)
 98% - Deutsch (de)
 92% - PortuguÃªs do Brasil (pt-br)
 86% - Japanese (ja)
 63% - French (fr)
 44% - Portuguese (pt)
 20% - Nederlands (nl)
```

**Comment by mauritsvanrees** [comment]
I have edited a few other translation jobs as well: [Plone 5.2 - Find strings](https://jenkins.plone.org/view/Translations/job/plone-5.2-i18n-find-missing/) and [Plone 5.2 - Translations](https://jenkins.plone.org/view/Translations/job/plone-5.2-i18n/) had the same problem.

The Python 2.7 variants of these two were already working. Actually, I think they might be the same. Anyway, that is a different issue.

**Comment by erral** [comment]
Thanks @mauritsvanrees! @gforcada added it for me, but i don't know how he did it

**Comment by gforcada** [comment]
I was lazy to add it on jenkins repo configuration and did it manually 😓
