### ISSUE TITLE
Include new pkg plone.base in PR handling.

### ISSUE THREAD

**Issue by jensens** [plone/jenkins.plone.org#296]
Please add `plone.base` to the automatic pull request handling. Thanks!

**Comment by mauritsvanrees** [comment]
On https://jenkins.plone.org/roboto/ I clicked on "Re-create GitHub commit hooks", with a secret token. That should do the trick. Can take a while though.
Also, once done, I should probably disable it again on the `documentation` repo, as I did earlier this week. But that is another discussion.

**Comment by mauritsvanrees** [comment]
Done. The web hooks have been set:
https://github.com/plone/plone.base/settings/hooks
