### ISSUE TITLE
Remove Python 3.7 from Plone 6.0 jobs

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#308]
See https://github.com/plone/Products.CMFPlone/issues/3635
It is fine if the 3.7 jobs are kept available for now, we do not need to completely delete them just yet.
But they should not be added to the "pending" status checks on PRs.
And when someone says "Jenkins please run jobs", then only 3.8, 3.9 and 3.10 should be started.

@gforcada Am I right that this is not in code anywhere, but is a registry setting somewhere on the main Jenkins machine? Could you update this setting please?

**Comment by gforcada** [comment]
🤔 yes, I think that's a setting on mr.roboto, I will update it right away! 🐌

**Comment by gforcada** [comment]
@mauritsvanrees it should be deployed ✨ let me know if it works

**Comment by mauritsvanrees** [comment]
I have merged a PR and then jobs for 3.7 and 3.7 robot are still run.
The [polling log](https://jenkins.plone.org/job/plone-6.0-python-3.7/1673/pollingLog/) says this, if it helps:

```
Started on Sep 15, 2022, 8:52:33 PM
Started by event from 140.82.115.109 → 172.70.34.39 → 140.82.115.109 ⇒ https://jenkins.plone.org:8080/github-webhook/ on Thu Sep 15 20:52:31 CEST 2022
Polling SCM changes on Node4
Using strategy: Default
[poll] Last Built Revision: Revision 14c5fa98b515d63811e7988fbe2e8360b9584d21 (origin/6.0)
The recommended git tool is: NONE
No credentials specified
 > git rev-parse --resolve-git-dir /home/jenkins/workspace/plone-6.0-python-3.7/.git # timeout=10
Fetching changes from the remote Git repositories
 > git config remote.origin.url https://github.com/plone/buildout.coredev.git # timeout=10
Using shallow fetch with depth 10
Fetching upstream changes from https://github.com/plone/buildout.coredev.git
 > git --version # timeout=10
 > git --version # 'git version 2.34.1'
 > git fetch --no-tags --force --progress --depth=10 -- https://github.com/plone/buildout.coredev.git +refs/heads/*:refs/remotes/origin/* # timeout=10
Polling for changes in
 > git rev-parse origin/6.0^{commit} # timeout=10
 > git log --full-history --no-abbrev --format=raw -M -m 14c5fa98b515d63811e7988fbe2e8360b9584d21..e08c19378062b436169a7d526eb3cb6887549f3c # timeout=10
Done. Took 1.4 sec
Changes found
```

So the standard two 3.7 jobs fore coredev 6.0 are still triggered. This should still be changed.

I have created another [PR](https://github.com/plone/Products.CMFPlone/pull/3644). After triggering Jenkins with the comment, only jobs for 3.8, 3.9 and 3.10 were run. So that part is good.

**Comment by davisagli** [comment]
@mauritsvanrees Is it okay to go ahead and fully delete the Plone 6.0 - Python 3.7 jobs? It looks like it is probably easier to do that than to keep them but disable the automatic triggering.

**Comment by mauritsvanrees** [comment]
That should be fine. There is very little historical value in keeping them.

**Comment by mauritsvanrees** [comment]
I have logged into the jenkins.plone.org website and have delete all Plone 6.0 3.7 jobs.
I will make a PR to remove them from `jobs.yml` as well.
