### ISSUE TITLE
Plone 5.2 Python 3.6 jobs fail

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#310]
See for example [here](https://jenkins.plone.org/job/plone-5.2-python-3.6/1771/console)

```
[plone-5.2-python-3.6] $ /bin/sh /tmp/jenkins6153739878114500710.sh
Error: Command
 '['/home/jenkins/workspace/plone-5.2-python-3.6/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']'
died with <Signals.SIGSEGV: 11>.
/tmp/jenkins6153739878114500710.sh: 5: .: cannot open venv/bin/activate: No such file
Build step 'Execute shell' marked build as failure
```

**Comment by davisagli** [comment]
It looks like the Python 3.6 installed by https://github.com/gforcada/ansible-compile-python is segfaulting while trying to install pip.

It might be the same issue as https://bugs.python.org/issue45700 -- that issue has some suggestions for workarounds by adding environment variables while compiling Python

**Comment by gforcada** [comment]
@davisagli nice finding!! 💯 I'm not really sure how to apply the suggestions though 😕 the script that installs python is: https://github.com/gforcada/ansible-compile-python/blob/master/tasks/python_generic.yml we only pass the generic `--enable-optimizations`.

On the nodes we have gcc 11 and the whole point of using this `ansible-compile-python` was exactly to squeeze a bit more of performance, so if we have to now revert to `-O2` seems like we could basically remove `ansible-compile-python` completely 🤷🏾 

@mauritsvanrees removing 3.6 support for 5.2 (not actively, but not running the tests) would be an option from release management? Users already have 2 other python3 versions to upgrade to (3.7 and 3.8) and anyway 3.6 is out of security support anyway. 3.7 will be EOL in a year and for 3.8 there are still 2 years to go.

May I disable 3.6 on mr.roboto (so it don't ask to get CI to pass to merge a PR?) meanwhile? 🤔

**Comment by davisagli** [comment]
@gforcada I agree it seems we can't safely turn on the optimizations for Python 3.6, at least not without doing a deep dive that doesn't seem worth it for such an old Python.

**Comment by mauritsvanrees** [comment]
What if we turn the optimisations off? Would that help, without making the tests take a lot longer? Or would we then need to remove ansible-compile-python for 3.6 and install it in a different way than all the others?

I would rather keep it. But I agree it does not make sense to put a lot of time in an unsupported Python version. When the tests pass on 2.7, 3.7 and 3.8, it is likely they also pass on 3.6. We already do a [`bin/test -u`](https://github.com/plone/buildout.coredev/blob/5.2/.github/workflows/run-buildout.yml#L52) on coredev 5.2 on all Python versions, so the basic failures would still get caught. We might expand this on 3.6 to run the full test suite.

So: if 3.6 on Jenkins can be fixed without too much more hassle, then that would be nice. Otherwise we drop it.
We needed some fixes on Jenkins to test Plone on a newer OS with latest browser versions and proper 3.10 support. Losing 3.6 is an unfortunate fall-out from this much needed work. I can live with that.

**Comment by gforcada** [comment]
As you say, I would rather put the focus on 3.10 and getting 6.0 out rather than keeping ourselves busy with doing some code bending to get 3.6 to work for 5.2

**Comment by mauritsvanrees** [comment]
Agreed.

@plone/release-team Due to needed improvements on Jenkins, we are losing Python 3.6 support on Plone 5.2. At least: testing this version is not going to work anymore with reasonable effort. It has been end of life since [December last year](https://devguide.python.org/versions/).
Running the tests on 2.7 still works, so it is unlikely that we will introduce a real error on 3.6. But it may happen.
I might try adding a GitHub-actions job on coredev 5.2 to test 3.6, if that does not take too much time to setup. Maybe only running `bin/test -u`.

I will add something to the release notes of 5.2.10, planned for next month. Or add a separate post on community sooner.

**Comment by mauritsvanrees** [comment]
I have written a [post on community](https://community.plone.org/t/plone-5-2-drops-python-3-6-support/15706).

Could one of you take care of removing the Plone 5.2 Python 3.6 core jobs, PR jobs, pending statuses, please?

**Comment by mauritsvanrees** [comment]
Thanks!
