### ISSUE TITLE
Jenkins PR jobs failed getting pygithub 1.43

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#312]
@davisagli already fixed this manually yesterday while switching planes, but the same should be done in the scripts/config as well, so I open this issue so we don't forget about it.

See https://jenkins.plone.org/job/pull-request-6.0-3.10/155/console
Installing pygithub fails:
error in PyGithub setup command: use_2to3 is invalid.

Coredev itself has a pin, which is 1.55, which should never have this problem. But Jenkins jobs and scripts use a different version.
1.56 is out recently, which officially support Python 3.10.

@davisagli will you pick this up?

**Comment by mauritsvanrees** [comment]
I now see that the 5.2 PR jobs have the same problem. See this [5.2-2.7 job](https://jenkins.plone.org/job/pull-request-5.2-2.7/2404/console), which is actually the first such job to run since the end of August:

```
[pull-request-5.2-2.7] $ /srv/python3.9/bin/python3.9 /home/jenkins/shiningpanda/jobs/34b418f2/virtualenv.py /home/jenkins/shiningpanda/jobs/34b418f2/virtualenvs/0dd3bfc1
/home/jenkins/shiningpanda/jobs/34b418f2/virtualenv.py:1041: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Using base prefix '/srv/python3.9'
New python executable in /home/jenkins/shiningpanda/jobs/34b418f2/virtualenvs/0dd3bfc1/bin/python3.9
Also creating executable in /home/jenkins/shiningpanda/jobs/34b418f2/virtualenvs/0dd3bfc1/bin/python
Installing setuptools, pip, wheel...done.
[pull-request-5.2-2.7] $ /bin/sh -xe /tmp/shiningpanda12764565218062517776.sh
+ pip install pygithub==1.43.2
Collecting pygithub==1.43.2
  Using cached PyGithub-1.43.2.tar.gz (2.7 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in PyGithub setup command: use_2to3 is invalid.
      [end of output]
```

Note that this is a Python 2.7 job, but it already goes wrong in the setup, where 3.9 is used.

Also, I see that this error is first raised by [setuptools 58](https://setuptools.pypa.io/en/latest/history.html#v58-0-0). So an option could be to let this part of the scripts use an older setup tools. But the most recent pygithub should be fine as well.

**Comment by davisagli** [comment]
@mauritsvanrees Done -- and I updated the 5.2 PR jobs as well

**Comment by mauritsvanrees** [comment]
@davisagli Thanks!

All PR jobs work, except for the 5.2-2.7 one. See [console log](https://jenkins.plone.org/job/pull-request-5.2-2.7/2406/console):

```
$ /home/jenkins/shiningpanda/jobs/34b418f2/virtualenvs/0dd3bfc1/bin/python /tmp/shiningpanda3979182560506241711.py
[EnvInject] - Injecting environment variables from a build step.
[EnvInject] - Injecting as environment variables the properties file path 'vars.properties'
[EnvInject] - Variables injected successfully.
[pull-request-5.2-2.7] $ /bin/sh /tmp/jenkins3422780263022338227.sh
/tmp/jenkins3422780263022338227.sh: 8: pip: not found
/tmp/jenkins3422780263022338227.sh: 9: buildout: not found
/usr/bin/xvfb-run: 184: bin/test: not found
/tmp/jenkins3422780263022338227.sh: 23: python: not found
```

**Comment by mauritsvanrees** [comment]
I don't see how this would be related to your changes to the pygithub version. It can be that the 2.7 was broken by earlier changes: no one started such a job in September and October.

**Comment by davisagli** [comment]
@mauritsvanrees The Plone 5.2 Python 2.7 PR job is now working: https://github.com/plone/jenkins.plone.org/commit/d9fe784c9399a1f85097f8204b2064b64e9f5439

**Comment by mauritsvanrees** [comment]
Thanks!
