### ISSUE TITLE
Create Python 3.11 PR job

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#314]
A Plone 6.0 Buildout on 3.11 now finishes correctly on Jenkins. But lots still goes wrong. See https://github.com/plone/buildout.coredev/issues/821.

It would help if there is a 3.11 PR job, so we can try things out.
For now it is best to only make this available for manual use. So do **not** run it automatically when someone adds the comment to ask Jenkins to run the jobs.

Note that the main 3.11 job is disabled. I enabled it yesterday to see the effect of the recent lxml update, but disabled it again this morning.

Low priority: 3.11 support is not needed for Plone 6.0 final. But it would be cool to have.

**Comment by gforcada** [comment]
This morning I made a new version of the [ansible playbook](https://galaxy.ansible.com/gforcada/compile-python) we use to install python on the servers, I will deploy it during the day or at night, so we can use python 3.11 final release 😄

**Comment by mauritsvanrees** [comment]
Ah, cool.
I did not see that there was a final release yet, out yesterday I see now.
