### ISSUE TITLE
Mismatch between chromedriver and chrome

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#316]
See for example this [console log](https://jenkins.plone.org/job/pull-request-6.0-3.10/197/console)

```
Setup failed:
SessionNotCreatedException:
Message: session not created:
This version of ChromeDriver only supports Chrome version 105
Current browser version is 107.0.5304.68 with binary path /usr/bin/google-chrome
```

I guess there was a recent update to one of them, and the other needs to catch up.

I only see this in PR jobs, but looks like the normal jobs simply were not run the past day. A new [6.0 3.10 robot job](https://jenkins.plone.org/job/plone-6.0-python-3.10-robot-chrome/542/console) fails as well.

**Comment by gforcada** [comment]
😅 I just mentioned that I fixed that on discord 😄 

Yes, sorry for breaking it, yesterday I was updating the nodes and jenkins itself to the newer versions, plus newer python versions, and seems that we will have to be careful with this updates, as chrome gets updated, but not chromedriver 😕 we have to do that manually.

Fortunately is a matter of downloading and upacking a zip file 😄
