### ISSUE TITLE
Add Python 3.11 robot job

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#317]
The main Plone 6.0 Python 3.11 job is green: https://jenkins.plone.org/job/plone-6.0-python-3.11/148/
But we don't run robot tests yet. Could someone add this please? Thanks.
They should pass fine: the 3.11 PR job does run them: https://jenkins.plone.org/job/pull-request-6.0-3.11/5/

**Comment by gforcada** [comment]
Created:

- https://jenkins.plone.org/job/plone-6.0-python-3.11/
- https://jenkins.plone.org/job/plone-6.0-python-3.11-robot-chrome/
- https://jenkins.plone.org/job/pull-request-6.0-3.11/

Now their configuration comes from jenkins.plone.org configuration. See the incoming PR 😄

**Comment by mauritsvanrees** [comment]
Thanks, that works.

Now the jobs should be started automatically when appropriate. I think some already start, but we should check:

- [ ] Start 3.11 Python job on commit to coredev 6.0.
- [ ] Start 3.11 Robot job on commit to coredev 6.0.
- [ ] Add 3.11 PR job to the list of expected/recommended checks when a PR is created.
- [ ] Start 3.11 PR job when someone uses the "mr-roboto please start jobs" comment.

**Comment by gforcada** [comment]
yup, that's a config change on `mr.roboto`.

I applied that, let's see if that simple change was enough 🤞🏾 😄
