### ISSUE TITLE
Jenkins fails to add comment to PR. Manual hooks problem?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#329]
Recently a few repos were deleted and restored, especially plone.app.event and plone.app.linkintegrity.  I manually recreated the web hooks: updating the hooks on all repos automatically gave rate limiting problems in the logs. I *think* I added the right secret as well, unless this should be a different secret than what we use in some urls on https://jenkins.plone.org/roboto/

I tried the 'Jenkins please run jobs' comment on this PR from a few days ago:
https://github.com/plone/plone.app.event/pull/1
It started jobs, which is good, but they all failed, for example this one:
https://jenkins.plone.org/job/pull-request-6.0-3.11/245/console
Failure message is:

Could not update Pull Request https://github.com/plone/plone.app.event/pull/1
Please contact the testing team: https://github.com/orgs/plone/teams/testing-team
Fill an issue as well: https://github.com/plone/jenkins.plone.org/issues/new

@gforcada Maybe you can see what I missed?

**Comment by gforcada** [comment]
As I added the _add hooks on a single repo_ let's try that 🤞🏾

**Comment by gforcada** [comment]
`plone.app.event` and `plone.app.linkintegrity` hooks have been restored 😄 

Are there any other repos that need hooks to be restored?

**Comment by mauritsvanrees** [comment]
Nope, that should be it. Thanks!
