### ISSUE TITLE
Plone 6.1 on Python 3.11 job

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#332]
I think @petschki / @thet / @mauritsvanrees mentioned that somewhere, right? 😅 

There you are then: 🪄 

https://jenkins.plone.org/job/pull-request-6.1-3.11/

Is enough to test PRs? 🤔 

So far `mr.roboto` is not being updated, and thus it will not ask add a _waiting_ job on the PR actions, I guess that's what we want for now, right?

Should we add the regular jobs as well? 🤔

**Comment by mauritsvanrees** [comment]
We will want the _waiting_ jobs as well, but it is probably fine to wait a few weeks so the new jobs can be tried out and are stable before throwing extra jobs on almost all PRs.

It *would* be good to have this prepared before the Beethoven sprint though, so it is easy to switch this on then if we want to go for it.  But yes, can be a nice topic for the first sprint day as well. :-)

We want regular jobs as well, yes.  Maybe only 3.11 for now, plus a job for 3.11 robot tests?  Or add them all in one go if that is easy.  We can always hide the 3.8-3.10 jobs at first so they only show up when you go the the 'All' tab, so the main page is not overflowing with jobs.

**Comment by gforcada** [comment]
You said before Beethoven sprint? well let's do that then 😄 ⛏️

**Comment by mauritsvanrees** [comment]
Thanks!
