### ISSUE TITLE
Plone 5.2 Py 2.7 robot job fails: Chrome failed to start

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#334]
The last three jobs failed, for example [this one](https://jenkins.plone.org/job/plone-5.2-python-2.7-robot-chrome/1962/).

```
Setup failed:
WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /snap/chromium/2424/usr/lib/chromium-browser/chrome
 is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

**Comment by mauritsvanrees** [comment]
It seems to be specific to Node 1.  For example here is another one already from 6 days ago:
https://jenkins.plone.org/job/plone-5.2-python-2.7-robot-chrome/1935/

**Comment by gforcada** [comment]
I've seen it, but I'm not sure about how to fix it 😖 let me have a look... 🤞🏾

**Comment by gforcada** [comment]
somehow the chromedriver, which we update manually, was _too new_ 🤷🏾 

It should be fixed: https://jenkins.plone.org/job/plone-5.2-python-2.7-robot-chrome/1978/console

**Comment by mauritsvanrees** [comment]
Thanks! Green indeed.

**Comment by davisagli** [comment]
@gforcada Thanks for fixing it! I took a short look last week but couldn't figure it out
