### ISSUE TITLE
Future of Mr.Roboto

### ISSUE THREAD

**Issue by bloodbare** [plone/jenkins.plone.org#34]
Now is taking care or all hooks on GH and launching the jobs that are needed. It takes care of a DB of plips that allow to create jobs/plip.

What should be the future of Mr.Roboto:

* creating a standalone configuration for singlepackage testing ( is not Travis doing this?)

* Pull request tests ??

* Saving the history of broken commits and working commits for plone.org stats.

* A way that people could create themselves as slaves that serve jenkins on sprints. People can download the vagrant installation of plone and connect with jenkins with a Reverse SSH tunnel and allow to be used as slaves. Mr.roboto could check and take care about this.

**Comment by tisto** [comment]
we are all happy with the current status of mr.roboto and our jenkins setup.
