### ISSUE TITLE
Node 3 status

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#349]
@ale-rt (if I remember correctly) was the donor of the `Node3` (and `Node4`!) for jenkins.plone.org

For a while (a few weeks/months) the `Node3` has not been available, is the server down due to maintenance or so? 🤔 can we expect to get it at some point up again? 🍀 

Otherwise I will remove it from jenkins.plone.org 🧹

**Comment by ale-rt** [comment]
Sorry, I noticed this just now!

**Comment by ale-rt** [comment]
You should be able to login again on the node.

However the node seems outdated:
![image](https://github.com/plone/jenkins.plone.org/assets/1300763/d54ea5c1-fc85-4324-8b74-7c0459a9d179)

**Comment by ale-rt** [comment]
> @ale-rt (if I remember correctly) was the donor of the `Node3` (and `Node4`!) for jenkins.plone.org
> 

Node 4 is from Syslab :)

**Comment by gforcada** [comment]
Cool, thanks! 😄

**Comment by gforcada** [comment]
It is again up and running 🎉 😄
