### ISSUE TITLE
Plone 6.1: drop jobs for Python 3.8 and 3.9

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#353]
See https://github.com/plone/Products.CMFPlone/issues/3926.

**Comment by gforcada** [comment]
Jenkins jobs updated and `mr.roboto` configuration as well 🎉 

`mr.roboto` configuration looks like this now:

```python
plone_versions = ['5.2', '6.0', '6.1' ]
py_versions = {'5.2': ['2.7', '3.8'], '6.0': ['3.8', '3.11'], '6.1': ['3.10', '3.12']}
```

**Comment by mauritsvanrees** [comment]
Thanks!
I noticed one error in the PR, made a comment there.
