### ISSUE TITLE
Chrome driver mismatch on Jenkins node 1

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#358]
@gforcada I think you saw this too, at least on [this job](https://jenkins.plone.org/job/pull-request-6.1-3.10/115/) I see: "Started by Naginator after the failure of build [#114](https://jenkins.plone.org/job/pull-request-6.1-3.10/114/). Started by user Gil Forcada Codinachs"

That job 114 was started by me after 113 failed in the same way:

```
Setup failed:
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 107
Current browser version is 124.0.6367.201 with binary path /usr/bin/google-chrome
```

This job is Plone 6.1 on Python 3.10.  The [PR itself](https://github.com/plone/buildout.coredev/pull/930) should be innocent.  The three failures are all on Node 1.

The [3.12 job passed](https://jenkins.plone.org/job/pull-request-6.1-3.12/356/).  This was on Node 3.

I started the normal (non-PR) [6.1-py-312-robot job](https://jenkins.plone.org/job/plone-6.1-python-3.12-robot-chrome/333/) and this is now being executed on Node 1 as well. Let's see if that one also fails.  I would expect so.

I started the [PR job for 3.10](https://jenkins.plone.org/job/pull-request-6.1-3.10/116/) and that is now executing on Node 3.  I would expect this to pass.

**Comment by gforcada** [comment]
I saw it indeed, let me see why is working on `Node3` but not on `Node1`.

Probably I don't have time until at night though 😕

**Comment by gforcada** [comment]
Fixed: https://jenkins.plone.org/job/plone-6.1-python-3.12-robot-chrome/339/console 🍀

**Comment by mauritsvanrees** [comment]
Great, thank you!
