### ISSUE TITLE
Chrome driver mismatch on Jenkins node 1

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#362]
Jenkins seems much too unstable the last few weeks.  What I most often see, is that all robot tests are broken, so that is something in the general setup.

Let's look at [Node 1](https://jenkins.plone.org/computer/Node1/builds) and with "Pull Request 6.1 on py3.10".  Latest is [283](https://jenkins.plone.org/job/pull-request-6.1-3.10/283/console), which is broken:

```
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 124
Current browser version is 127.0.6533.99 with binary path /usr/bin/google-chrome
```

Same for [PR 6.0 on Python 3.8](https://jenkins.plone.org/job/pull-request-6.0-3.8/lastCompletedBuild/console).

Node 3 also seemed unstable with robot tests, see for example [this one](https://jenkins.plone.org/job/plone-6.0-python-3.11-robot-chrome/1375/console):

```
Setup failed:
SessionNotCreatedException: Message: session not created
from unknown error: cannot create temp dir for user data dir
```

So that sounds different.

I do see calls to `bin/rfbrowser init` in both cases, which *should* make things work, but apparently not.

**Comment by gforcada** [comment]
This was fixed yesterday, sorry about it, I updated the servers but did not catch that chrome was updated and the chromedriver was then out of sync 😕 

Fortunately, downloading the chromedriver and installing is a breeze :)

**Comment by mauritsvanrees** [comment]
Thanks!
