### ISSUE TITLE
Python 3.13

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#371]
Zope 5.11 is out since today and it supports Python 3.13.
I [started testing Plone](https://github.com/plone/buildout.coredev/pull/956), but that needs some work.  Maybe we just need to update a bunch of dependencies to their latest versions, especially so more binary wheels will be available for 3.13.

But it would require some changes in Jenkins and mr.roboto.  For starters, Python 3.13 would need to be installed on the nodes.  I can imagine this is not yet available in the apt repo.

**Comment by davisagli** [comment]
Maybe we should install `uv` on the nodes and start using it to install Python. https://docs.astral.sh/uv/guides/install-python/

**Comment by gforcada** [comment]
@davisagli that would be a wonderful idea ✨ for now, we are compiling Python ourselves, as it was a way to get a speed boost, but maybe, it's no longer needed? 🤔 we could at least try it.

**Comment by mauritsvanrees** [comment]
Thanks for adding Python 3.13 Gil!

For now the coredev code and versions are not ready yet though, so running it always may not be good yet.  Then again, we should come close with [this PR](https://github.com/plone/buildout.coredev/pull/961).

**Comment by mauritsvanrees** [comment]
Python 3.13.1 has been released this week.  Is it already possible to update the Jenkins nodes to use this version?  This release solves a problem with the `pickle` module that bit us and made lots of tests fail (and gave an error when adding a page and versioning it).  Locally this makes `bin/test` pass (except for a few failures/errors related to PDF indexing, which should be only local.)

**Comment by gforcada** [comment]
On Node1 3.13.1 is updated, on Node5 @petschki is the master 😄

**Comment by petschki** [comment]
Updated on Node5 ... I gave the build a try here https://jenkins.plone.org/job/plone-6.1-python-3.13/106/console

**Comment by petschki** [comment]
And its green https://jenkins.plone.org/job/plone-6.1-python-3.13/106/

**Comment by petschki** [comment]
robottests also https://jenkins.plone.org/job/plone-6.1-python-3.13-robot-chrome/108/ 

🍺

**Comment by mauritsvanrees** [comment]
Awesome, thanks!
