### ISSUE TITLE
Define and implement best practice for running Javascript unit tests.

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#38]
Asko wrote #37: And something we are completely missing: best practices for writing and running javascript unit tests. Ross made Buster.JS integration for zope.testrunner during SeaSprint, but Rok prefers pure javascript-tools. @garbas, how would you integrate plone.mockup tests for Jenkins?

**Comment by gforcada** [comment]
We now have this: http://jenkins.plone.org/view/All/job/plone-5.0-js/ although it only runs tests for mockup, which is probably fine?

Should we promote this job to the main tab? The nice thing about this job is that it integrates nicely with github as it's a real 1:1 repository - jenkins job...
