### ISSUE TITLE
Build vagrant box to be used as temporary jenkins slaves during sprints

### ISSUE THREAD

**Issue by datakurre** [plone/jenkins.plone.org#39]
Not a priority.

A way that people could create themselves as slaves that serve jenkins on sprints. People can download the vagrant installation of plone and connect with jenkins with a Reverse SSH tunnel and allow to be used as slaves. Mr.roboto could check and take care about this.

@bloodbare should figure out, how those slaves could register themselves in a secure manner. @datakurre could do the vagrant part.

Open questions (in addition to how to authenticate):
- can we reuse existing vagrant box or should we build a custom box (building can be automated with veewee and jenkins); box specs?
- can sprint specific slaves somehow build only sprint related jobs? does it matter?

**Comment by gforcada** [comment]
*(three years later)* We most probably want to end up using docker, although no work has been started on that.

Right now though, with the new server donated by the foundation since the last Plone Conference and a new another one on the pipeline being donated, probably the need is not that high anymore.

**Comment by gforcada** [comment]
Given that our workload is CPU bound (with moderate disk usage and really low RAM usage) hetzner.de has quite some cheap servers on sale that takes me ~1h (mostly waiting to compile python 3.6 and 3.7) to get a new server online and available on jenkins.

One can find suitable servers for way less than 100EUR, so the Foundation or a generous sponsor could easily fund a server for a month.

One only needs to ping someone, right now me, to set it up some days before the sprint starts and then remember to cancel if it is no longer needed.
