### ISSUE TITLE
System monitoring for jenkins.plone.org

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#4]
I would like to have some kind of system monitoring service on jenkins.plone.org (and for the slave(s) as well). I would like to know how the machines handle the test load and to see if we need more machines.

Munin is easy to set up and will give us enough information. Any objections to that? Any takers?

I guess we don't have any fabric scripts or something similiar to set up jenkins.plone.org or the slaves in a documented and repeatable manner?

**Comment by gforcada** [comment]
We do have munin on master, not sure about nodes, should we turn jenkins master into a munin master as well? So all nodes report munin data to it? I would say that it makes sense for me.

**Comment by tisto** [comment]
+1

**Comment by tisto** [comment]
I created a new issue for nodes: https://github.com/plone/jenkins.plone.org/issues/107
