### ISSUE TITLE
Allow Plone core developers to restart a Jenkins job.

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#44]
Currently there is no way a Plone core developer can restart a coredev job on Jenkins without a "dummy" commit. We have to find a way to allow that. Granting anonymous users the right to restart a job is too risky, therefore I guess we somehow have to enable LDAP authentication, right?

**Comment by gforcada** [comment]
Thanks to the GitHub Oauth plugin this will be fixed... closing.
