### ISSUE TITLE
Run tests for Archetypes-based packages in a different job for Plone 5

### ISSUE THREAD

**Issue by davisagli** [plone/jenkins.plone.org#51]
What would it take for us to move the tests for Archetypes-based packages to a separate job that is only triggered once the main job completes? We should still test compatibility with these packages for now, but they are lower priority, and separating them would make it possible to give feedback more quickly on failures in the main codebase.

I guess it would mean adding new buildout parts (test-at and alltests-at) and making sure that there's a jenkins job which uses those instead of bin/jenkins-alltests. I don't know more about how to proceed without spending some time learning how the jenkins buildout is set up.

**Comment by gforcada** [comment]
Closing...
