### ISSUE TITLE
wrong configuration for plone.app.widgets plip job

### ISSUE THREAD

**Issue by davisagli** [plone/jenkins.plone.org#53]
The plone.app.widgets plip job isn't running the correct set of commands. It's running the wrong buildout and the wrong test command. It should be running this:

```
$PYTHON27 bootstrap.py -c jenkins.cfg
bin/buildout -c plips/plip13476-mockup.cfg
bin/jenkins-alltests
bin/jenkins-code-analysis
bin/jenkins-test-coverage
```

(plip cfg, not jenkins.cfg, and jenkins-alltests instead of jenkins-test)

I don't know how to change the configuration without it getting overwritten. What needs to happen?

**Comment by gforcada** [comment]
Already fixed I hope... if not, please reopen.
