### ISSUE TITLE
slave.py: change pil to pillow ?

### ISSUE THREAD

**Issue by svx** [plone/jenkins.plone.org#55]
is there are a reason why we still depend on pil ? if we could use pillow we would be able to change the way of testing and installing python2.6 and 2.7 which would make the install faster, slave.py shorter, and we would not have to mess with system libs.

**Comment by gforcada** [comment]
@svx is this still relevant? A quick grep on plone.jenkins_node shows that we are actively not installing PIL from the OS and installing Pillow instead.

Feel free to re-open.
