### ISSUE TITLE
Create Jenkins job for pull request with JJB

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#63]
We need a Jenkins job to manually test pull request. Pass URL of the pull request and URL of the repository to the Jenkins job together with your e-mail address.

Jenkins will run buildout.coredev with your pull request and send you an email with the result.

Starting point: http://jenkins.plone.org/job/plone-5.0-python-2.7-test-pull-request/

We should implement that with Jenkins Job Builder right from the start though.

**Comment by gforcada** [comment]
There's a jenkins plugin for testing pull requests: https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin maybe that's also a starting point to investigate...

**Comment by tisto** [comment]
Done: http://jenkins.plone.org/view/All/job/pull-request/
Next step: allow user to provide an email adress for a notification.

**Comment by tisto** [comment]
We might be able to look up the email address from the jenkins user automatically: https://wiki.jenkins-ci.org/display/JENKINS/Build+User+Vars+Plugin

**Comment by gforcada** [comment]
Aha... I was about to say that is not really possible... but turns out it should!

http://jenkins.plone.org/user/tisto/configure shows your user email, so there should be a way to get that...

**Comment by tisto** [comment]
Cool!

**Comment by gforcada** [comment]
I was playing with https://wiki.jenkins-ci.org/display/JENKINS/Build+User+Vars+Plugin but seems it does not work as expected ... doesn't output anything if you add them on the shell nor on the email extension plugin... not sure how to debug that actually ...

**Comment by gforcada** [comment]
@tisto we didn't discuss specifically, but I think we can close this by now right? Let's create new issues if there are more improvements to be made.

**Comment by tisto** [comment]
+1
