### ISSUE TITLE
Create saucelabs tests with JJB.

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#66]
http://jenkins.plone.org/view/Sauce%20Labs/

We should probably talk to @datakurre about that.

**Comment by datakurre** [comment]
Sure! I'm interested in learning JJB, but have been busy lately :/

Timo Stollenwerk kirjoitti pe helmikuuta 13 08:33:51 2015 GMT+0200:

**Comment by gforcada** [comment]
Done with #71
