### ISSUE TITLE
Create jenkins jobs for PLIPs

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#68]

**Comment by tisto** [comment]
Task: extend plipbase.cfg to generate xml output that jenkins can read (I will work on that).

**Comment by gforcada** [comment]
@tisto should I leave it closed or do you want to be keep it open for the task that you mentioned?

Now that the script is there, we to:
- let everyone know about it (naming convention: plipXXXYYY.cfg - where XXX is a number and YYY anything)
- create a cron job to run the script and later jjb (although by now we could run it manually)

**Comment by tisto** [comment]
I'm still working on the PLIP jobs. See https://github.com/plone/Products.CMFPlone/issues/216#issuecomment-76532473

**Comment by gforcada** [comment]
Ok, I assign it to you then :)

Let me know if you need any help.
