### ISSUE TITLE
Install Munin on new Jenkins server.

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#72]
Since the current test server is just a VM with two cores it is important that we monitor the system in order to see if we have to upgrade to a more powerful machine.

**Comment by tisto** [comment]
@svx Can we use https://github.com/plone/ansible-playbook/tree/master/roles/munin-node ? Or does this only work if node and server are on different machines?

**Comment by svx** [comment]
On 02/14/2015 06:55 AM, Timo Stollenwerk wrote:
>
> @svx <https://github.com/svx> Can we use
> https://github.com/plone/ansible-playbook/tree/master/roles/munin-node
> ? Or does this only work if node and server are on different machines?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plone/jenkins.plone.org/issues/72#issuecomment-74363381>.
>
Hi,
should work, but you know that that role is also install a zope check
right
[https://github.com/plone/ansible-playbook/blob/master/roles/munin-node/files/monitors/plonezope_res]
right ?
In general you can run muin-node and server on the same machine, this is
good enough to get some overview what the box is doing, this is not
really handy if the box goes down, but well for just checking it is enough.
Just keep in mind that is it. This is not serious monitoring :), For
that you want to user tools :).

**Comment by tisto** [comment]
I installed munin on the Jenkins server (still work in progress):

https://github.com/plone/jenkins.plone.org/commit/fd7e92243f3fc0559033f343edd754cd0563ae93
https://github.com/plone/plone.jenkins_server/commit/f11fcac3fca1600b99cbe428a54f252bae7484f9

I'm not sure if we should password protect munin though. @svx @gforcada @bloodbare opinions?

**Comment by gforcada** [comment]
We could try to reuse https://galaxy.ansible.com/list#/roles/770 ?

Protecting munin... yeah why not... on the other hand, is the information there really sensible? I don't think so...

**Comment by tisto** [comment]
done.
