### ISSUE TITLE
Add Simple Theme Plugin to Jenkins.

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#73]

**Comment by gforcada** [comment]
You mean this one right? https://wiki.jenkins-ci.org/display/JENKINS/Simple+Theme+Plugin will add it later at night :)

**Comment by gforcada** [comment]
Done with https://github.com/plone/plone.jenkins_server/commit/2bee764dcc3bc73c59b6581d35f1eab5cb35bc23

**Comment by gforcada** [comment]
And also updated the submodule here with https://github.com/plone/jenkins.plone.org/commit/2d5d4b3125e16b2862cae66209980aa078102cea

We only need to run the playbook again
