### ISSUE TITLE
Improve jjb to support workflow definitions

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#74]
Currently jjb only knows about flow, freestyle, maven and matrix job definitions: http://ci.openstack.org/jenkins-job-builder/definition.html#modules

We need to add support for workflow jobs in order to be able to use jjb and workflow jobs together, and thus retain the ability to have one single place where to configure jenkins jobs.

**Comment by gforcada** [comment]
*/me first read documentation before stating things...*

So no, no need to improve jjb, it already supports it: http://ci.openstack.org/jenkins-job-builder/project_flow.html

**Comment by gforcada** [comment]
*/me read the documentation properly and try it before stating things...*

So no, jjb supports the old DSL approach one, not the new format. Reopening...

**Comment by tisto** [comment]
Ok. So what options do we have other than waiting for jjb to implement this? Is it hard to implement this ourself? Can we just push a config.xml with jjb?

**Comment by gforcada** [comment]
Shouldn't be a problem to do it on our own fork of jjb, it's a matter of copying on of the others jjb job definitions and adapt (so basically copy&paste and start changing names around)

I will try to work on it during this week, I got injured and a vaccination for it, and it's a bit difficult to concentrate :S

**Comment by gforcada** [comment]
So, turns out it is not that difficult to add a bare minimum version of it...

I will try to polish it and send it for feedback during the week, hopefully today or tomorrow.

**Comment by gforcada** [comment]
Aaaand, with a bare-minimum version of it, it is now supported on our fork of JJB :) I created an example job so that we can play with it.

By now only externally referenced pipelines are supported.
