### ISSUE TITLE
jjb clone future

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#76]
Right now we have a submodule on this repo a clone of jjb on my personal account.

That's useful as long as I'm the only one adding changes to it, which shouldn't be much of a problem, but eventually (hopefully) others will also help.

So after this introduction: where should we keep our clone of jjb? can we really put it on plone github organization? I guess @polyester will say no, collective org then? Or is it ok to keep it on my own fork and give access to anyone that needs it?

The ideal world would be that all our changes are accepted upstream, but that always takes time and also doesn't help when you are working on some improvements, so we would most likely always need to have it as a dependency, at least in the sort term.

**Comment by polyester** [comment]
@gforcada that's not my call to make, although I do think it will be a bit messy in plone github organization. Theoretically it can be there, but since Apache2 is incompatible with GPL2 it all gets a bit confusing, to say the least.

Collective would probably be better.

**Comment by gforcada** [comment]
Just for reference: they are also asking for a CLA.

**Comment by gforcada** [comment]
The situation is far better now, we only have a few commits on top of their code and is really easy to maintain, and on top of that we don't really have to bump it that much frequently anyway.
