### ISSUE TITLE
Use Dashboard Views instead of regular views.

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#79]
The Jenkins dashboard plugin is already installed. We should make all views/tabs use dashboard views. At least the core view (which is the default one) has to use the dashboard view. For all others it does not really matter which type they use. cc @gforcada

**Comment by gforcada** [comment]
The basic change is done here: https://github.com/plone/plone.jenkins_server/commit/892a1c9a7d9c678f36d3e34067cb0e5ffeffbbc5

We are missing what needs to be displayed and so, if you have time to configure it manually, then we can extract the configuration and put it on plone.jenkins_server

**Comment by gforcada** [comment]
Done with https://github.com/plone/plone.jenkins_server/commit/95fd3112f3dc1c672255d8a9a520702412dd3a2e
