### ISSUE TITLE
'Authorize application' requests access to all public and private repos.

### ISSUE THREAD

**Issue by jaroel** [plone/jenkins.plone.org#81]
jenkins.plone.org requests full access to all my organizations.
I have no possibility to just allow access to the Plone organization.

This is a github issue imho, but filed here for tracking.

**Comment by gforcada** [comment]
actually I think the problem lies on the jenkins github oauth plugin. Somewhere it needs to define which permissions wants.

I failed to see where they are defined though...

**Comment by gforcada** [comment]
For reference, the plugin is: https://wiki.jenkins-ci.org/display/JENKINS/Github+OAuth+Plugin

**Comment by jaroel** [comment]
Oh, the permissions are fine. The plugin just requests access to all organizations :)

**Comment by jaroel** [comment]
Looks like a list of organizations can be passed in as the command line parameter 'orgs':
```console
java -jar jenkins-cli.jar -s http://localhost:8080 groovy security.groovy admins='{jenkins_admins}' orgs='plone,collective' clientid='{github_clientId}' clientsecret='{github_clientSecret}'
```

**Comment by gforcada** [comment]
Yeah we already have that, both plone and collective can be used: https://github.com/plone/jenkins.plone.org/blob/master/jenkins_server.yml#L17

**Comment by gforcada** [comment]
And is used here: https://github.com/plone/plone.jenkins_server/blob/master/templates/jenkins_config.xml.j2#L10

**Comment by gforcada** [comment]
If I understood it correctly the upstream bug for this is: https://github.com/jenkinsci/github-oauth-plugin/pull/35

**Comment by tisto** [comment]
It seems the bug has been fixed. I just upgraded the plugin and restarted Jenkins. After the login my github permissions were amended:
 
![jenkins-github-auth-fix](https://cloud.githubusercontent.com/assets/632105/11542238/c58de006-9936-11e5-9617-209615c9409e.png)
