### ISSUE TITLE
Check ansible playbook and make sure we use security best practices.

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#84]
https://github.com/plone/jenkins.plone.org/blob/master/jenkins_server.yml
https://github.com/plone/jenkins.plone.org/blob/master/jenkins_node.yml

**Comment by gforcada** [comment]
We could use [ansible vault](http://docs.ansible.com/ansible/playbooks_vault.html) to keep the secrets, which actually are just 3 github API keys and the private ssh key that connects master to nodes.

**Comment by gforcada** [comment]
If someone has time to look at it, please do so, meanwhile, I'm closing it.
