### ISSUE TITLE
Add jenkins node on vagrant

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#86]
Currently our Vagrantfile only defines one single vm: a jenkins master.

We need to update it to at least add one node so that we can not only test jenkins configurations and jjb created jobs but also if they actually run :)

**Comment by gforcada** [comment]
Just to report on the status, for whoever is interested on it:

both master and node playbooks work like a charm, the vms are already connected via a private network and the only missing piece is that jenkins master acknowledges that it has a node to run tests on. Hopefully this week this is done!

**Comment by svx** [comment]
Awesome !! Let me if if you want to have docker and later rocket container for this !

**Comment by gforcada** [comment]
The pull request takes over...
