### ISSUE TITLE
mr.roboto removes the jenkins github post-commit hook.

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#88]
The github post-commit was not present this morning here:

https://github.com/plone/buildout.coredev/settings/hooks

I suspect that the mr.roboto hooks removed the jenkins hook from buildout.coredev. Is that possible @bloodbare ?

**Comment by bloodbare** [comment]
Yes, I needed to rerun the hooks and it reset the hook.

I Updated mr.roboto code to try not to remove it when it reruns. I changed
the code of mr roboto so for each commit on sources.cfg and checkouts.cfg
at coredev it relaods the sources and checkouts so it will not be needed to
rereun the hook setting unless we create a new repo on plone namespace.

On the other hand, I've been figuring out how to deal the pull request
problem. I don't know if the github pluggin on jenkins will follow pull
requests on coredev, but a possible option would be that in case there is a
pull request on a package that is linked to a buildout.coredev we can
create throw mr.roboto a coredev branch, change the sources file to the
package checkouts the pulled version and do a pull request on coredev so
jenkins github can treat it as a pull request. The problem apears when a
pull request depends on another pull request.

Ramon

El dt., 3 març, 2015 a les 8:12, Timo Stollenwerk (<notifications@github.com>)
va escriure:

The github post-commit was not present this morning here:

**Comment by gforcada** [comment]
For the complex use case (PR that depend on others) I would say that the easiest is to follow the PLIPs route: create a cfg file (say that a ``pull-requests`` folder is created on buildout.coredev) and let jenkins job builder create a job for you.

For the simple use-case I still have to look at what the jenkins plugin does really allow us to do...

**Comment by gforcada** [comment]
Adding a cronjob could be the solution, although we do not have that many new packages every now and then, and some of them do not need the hooks to begin with...
