### ISSUE TITLE
Set up dependencies Jenkins job.

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#89]
We need a tab and the jobs we had on the old server. Ramon can fire up the old instance if necessary.

**Comment by gforcada** [comment]
I was planning on doing something like for PLIPs, create a "qa" folder or something like that on buildout.coredev and create jobs based on the .py/.sh files found there.

This way if anyone wants to add a new check/QA script is a matter of sending a pull request to buildout.coredev, get it merged and the job will be created on jenkins.

**Comment by tisto** [comment]
I think I would prefer to start simple (just create the dependencies jobs with jjb) and then automate things later if necessary.

**Comment by gforcada** [comment]
Ok, then, can we get the jobs config.xml so anyone can try to replicate them on jjb? @bloodbare could you spin up the old instance and give me access. Is just 5 minutes.

**Comment by bloodbare** [comment]
@gforcada ping me when you are online if you still need this access.

**Comment by gforcada** [comment]
@bloodbare sure, will do, sorry today was packed. Actually if you just send me (by mail) all those config.xml is more than enough too...

**Comment by gforcada** [comment]
Jobs are there, failing, due to not generating dot files, but that's irrelevant to this story...
