### ISSUE TITLE
mr.roboto commits last_commit.txt to buildout.coredev.

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#90]
I don't know why this is necessary but if we keep it like this we will see tons of merges in our commit log. To avoid this, developers need to do a git pull after every single push.

@bloodbare what's the rationale behind this?

**Comment by bloodbare** [comment]
No matter if we add last_commit.txt or not on the commit we do to coredev, we need to change the head of the 5.0 branch to write the commit and that means you need to rebase or merge. Coredev developers needs to do a pull -r so there is not merges.

**Comment by davisagli** [comment]
You can tell git to do that automatically; see the "Pull with rebase instead of merge" section on http://mislav.uniqpath.com/2010/07/git-tips/

**Comment by bloodbare** [comment]
@davisagli do you know if we can set the git configuration on the repository instead of configuring that localy ?

**Comment by davisagli** [comment]
I don't think so. You can put .gitconfig in the repository but it won't be used unless users include it from their ~/.gitconfig: http://stackoverflow.com/questions/18329621/storing-git-config-as-part-of-the-repository

**Comment by gforcada** [comment]
Totally agree here, ``git pull -r`` or better on .gitconfig is the only sane solution when working in shared repositories, there's no point on doing merge commits on commits that are only local to you or the branch you are developing on, keeping a sane git log history is quite important when doing forensics and digging out code.
