### ISSUE TITLE
Enhance the console output

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#91]
Whenever there are errors on a build it is usually (at least for me) more useful to go directly to the console output, so you have a bit more of context about what happened.

So I thought that coloring the console output would not be too bad right? So with my poor javascript-fu I created this:

```javascript
$ = jQuery;
var text_node = $('.task-link');

$('.console-output').each( function () {
  $(this).html($(this).text()
               .replace(/(\d+ tests)/g, '<span style="color:green">$1</span>')
               .replace(/([1-9]\d* failures)/g, '<span style="color:red">$1</span>')
               .replace(/([1-9]\d* errors)/g, '<span style="color:red">$1</span>')
               .replace(/([1-9]\d* skipped)/g, '<span style="color:red">$1</span>')
  );
});
```

Basically turns lines like this:
```Ran 4 tests with 0 failures, 2 errors and 0 skipped in 8.664 seconds.```

Into colorful ones :)

Question though, we are using this JS for the theme: https://cdnjs.cloudflare.com/ajax/libs/doony/2.1/js/doony.min.js

So we should now host our version of it to add this snippet right? Would it be ok to do that?

**Comment by gforcada** [comment]
Will create a Pull Request later on during the day

**Comment by tisto** [comment]
There are Jenkins plugins that can do this in Jenkins itself. One plugin is configurable with regular expressions. Running over the full console output with jQuery JS might lead to blocking the browser, so I'm not sure if this is a good idea.

**Comment by tisto** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/Log+Parser+Plugin

**Comment by gforcada** [comment]
I knew there was something out there :)

It was mostly a "let's try to do that and see how it looks like" rather than a must have.

Still the point of keeping the JS on jenkins.plone.org repo does make sense to me, as eventually we will want to add some small thingies here and there and so on.
