### ISSUE TITLE
Customize email send by pull request job.

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#94]
Subject: Jenkins Pull Request Job [STATUS]: PULL_REQUEST_PACKAG PULL_REQUEST_BRANCH

The Jenkins pull request job you requested has been finished:

http://JENKINS_JOB_URL

**Comment by gforcada** [comment]
Minor glitch fixed on https://github.com/plone/jenkins.plone.org/commit/c4b4e5943731c548241abf22ad3fa068452e0237
