### ISSUE TITLE
python headers for python 3

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#99]
I'm just tinkering around with a ZTK job to run it on python 3, just to keep sure that while we are still not so sure what to do with it, we at least know if it works or not.

Testing it with 2.7 works fine, see http://jenkins.plone.org/job/ztk/1 but running it with 3.4 gives an error:

```
src/zope/proxy/_zope_proxy_proxy.c:27:20: fatal error: Python.h: No such file or directory
 #include "Python.h"
                    ^
compilation terminated.
```

**Comment by gforcada** [comment]
With the newer plone.jenkins_node ansible playbook this is solved :)

**Comment by jnns** [comment]
If someone from the future stumbles in here looking for help: a missing `Python.h` probably means that your system is missing the Python development package (which provides the required header files).
